define(["jquery","jquerypp/compare"],function(o){(function(e){e.fn.range=function(){return e.Range(this[0])};var r=function(a){return a.replace(/([a-z])([a-z]+)/gi,function(a,c,d){return c+d.toLowerCase()}).replace(/_/g,"")},o=function(a){return a.replace(/^([a-z]+)_TO_([a-z]+)/i,function(a,c,d){return d+"_TO_"+c})},s;e.Range=function(a){if(this.constructor!==e.Range)return new e.Range(a);a&&a.jquery&&(a=a[0]);!a||a.nodeType?(this.win=a?a.ownerDocument.defaultView||a.ownerDocument.parentWindow:window,
this.range=this.win.document.createRange?this.win.document.createRange():this.win.document.body.createTextRange(),a&&this.select(a)):null!=a.clientX||null!=a.pageX||null!=a.left?this.moveToPoint(a):a.originalEvent&&a.originalEvent.touches&&a.originalEvent.touches.length?this.moveToPoint(a.originalEvent.touches[0]):a.originalEvent&&a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length?this.moveToPoint(a.originalEvent.changedTouches[0]):this.range=a};e.Range.current=function(a){var a=
a?a.ownerDocument.defaultView||a.ownerDocument.parentWindow:window,b;return a.getSelection?(b=a.getSelection(),new e.Range(b.rangeCount?b.getRangeAt(0):a.document.createRange())):new e.Range(a.document.selection.createRange())};e.extend(e.Range.prototype,{moveToPoint:function(a){var b=a.clientX,c=a.clientY;b||(c=p(),b=(a.pageX||a.left||0)-c.left,c=(a.pageY||a.top||0)-c.top);if(s)return this.range=e.Range().range,this.range.moveToPoint(b,c),this;for(var d=document.elementFromPoint(b,c),g=0;g<d.childNodes.length;g++){var f=
d.childNodes[g];if(3===f.nodeType||4===f.nodeType)for(var f=e.Range(f),j=f.toString().length,k=1;k<j+1;k++){var h=f.end(k).rect();if(h.left<=b&&h.left+h.width>=b&&h.top<=c&&h.top+h.height>=c){f.start(k-1);this.range=f.range;return}}}var i;l(d.childNodes,function(b){b=e.Range(b);if(b.rect().top>a.clientY)return!1;i=b});i?(i.start(i.toString().length),this.range=i.range):this.range=e.Range(d).range},window:function(){return this.win||window},overlaps:function(a){a.nodeType&&(a=e.Range(a).select(a));
var b=this.compare("START_TO_START",a),c=this.compare("END_TO_END",a);return 0>=b&&0<=c||0<=b&&0>=this.compare("START_TO_END",a)||0<=this.compare("END_TO_START",a)&&0>=c?!0:!1},collapse:function(a){this.range.collapse(void 0===a?!0:a);return this},toString:function(){return"string"==typeof this.range.text?this.range.text:this.range.toString()},start:function(a){if(void 0===a){if(this.range.startContainer)return{container:this.range.startContainer,offset:this.range.startOffset};var b=this.clone().collapse().parent(),
a=e.Range(b).select(b).collapse();a.move("END_TO_START",this);return{container:b,offset:a.toString().length}}this.range.setStart?"number"==typeof a?this.range.setStart(this.range.startContainer,a):"string"==typeof a?(b=t(this.range.startContainer,this.range.startOffset,parseInt(a,10)),this.range.setStart(b.node,b.offset)):this.range.setStart(a.container,a.offset):"string"==typeof a?this.range.moveStart("character",parseInt(a,10)):(b=this.start().container,"number"!=typeof a&&(b=a.container,a=a.offset),
b=e.Range(b).collapse(),b.range.move(a),this.move("START_TO_START",b));return this},end:function(a){if(void 0===a){if(this.range.startContainer)return{container:this.range.endContainer,offset:this.range.endOffset};var b=this.clone().collapse(!1).parent(),a=e.Range(b).select(b).collapse();a.move("END_TO_END",this);return{container:b,offset:a.toString().length}}this.range.setEnd?"number"==typeof a?this.range.setEnd(this.range.endContainer,a):"string"==typeof a?(b=t(this.range.endContainer,this.range.endOffset,
parseInt(a,10)),this.range.setEnd(b.node,b.offset)):this.range.setEnd(a.container,a.offset):"string"==typeof a?this.range.moveEnd("character",parseInt(a,10)):(b=this.end().container,"number"!=typeof a&&(b=a.container,a=a.offset),b=e.Range(b).collapse(),b.range.move(a),this.move("END_TO_START",b));return this},parent:function(){if(this.range.commonAncestorContainer)return this.range.commonAncestorContainer;var a=this.range.parentElement(),b=this.range;l(a.childNodes,function(c){if(e.Range(c).range.inRange(b))return a=
c,!1});return a},rect:function(a){var b=this.range.getBoundingClientRect();!b.height&&!b.width&&(b=this.range.getClientRects()[0]);"page"===a&&(a=p(),b=e.extend({},b),b.top+=a.top,b.left+=a.left);return b},rects:function(a){for(var b=e.map(e.makeArray(this.range.getClientRects()).sort(function(a,b){return b.width*b.height-a.width*a.height}),function(a){return e.extend({},a)}),c=0,d;c<b.length;){var g=b[c],f=!1;for(d=c+1;d<b.length;)if(m(g,{clientX:b[d].left,clientY:b[d].top})&&m(g,{clientX:b[d].left+
b[d].width,clientY:b[d].top})&&m(g,{clientX:b[d].left,clientY:b[d].top+b[d].height})&&m(g,{clientX:b[d].left+b[d].width,clientY:b[d].top+b[d].height}))if(b[d].width){f=b[d];break}else b.splice(d,1);else d++;f?b.splice(c,1):c++}if("page"==a){var j=p();return e.each(b,function(a,b){b.top+=j.top;b.left+=j.left})}return b}});(function(){var a=e.Range.prototype,b=e.Range().range;a.compare=b.compareBoundaryPoints?function(a,b){return this.range.compareBoundaryPoints(this.window().Range[o(a)],b.range)}:
function(a,b){return this.range.compareEndPoints(r(a),b.range)};a.move=b.setStart?function(a,b){var c=b.range;switch(a){case "START_TO_END":this.range.setStart(c.endContainer,c.endOffset);break;case "START_TO_START":this.range.setStart(c.startContainer,c.startOffset);break;case "END_TO_END":this.range.setEnd(c.endContainer,c.endOffset);break;case "END_TO_START":this.range.setEnd(c.startContainer,c.startOffset)}return this}:function(a,b){this.range.setEndPoint(r(a),b.range);return this};var c=b.cloneRange?
"cloneRange":"duplicate";a.clone=function(){return e.Range(this.range[c]())};a.select=b.selectNodeContents?function(a){a?this.range.selectNodeContents(a):(a=this.window().getSelection(),a.removeAllRanges(),a.addRange(this.range));return this}:function(a){if(a)if(3===a.nodeType){var b=a.parentNode,c=0,e;l(b.childNodes,function(b){if(b===a)return e=c+b.nodeValue.length,!1;c+=b.nodeValue.length});this.range.moveToElementText(b);this.range.moveEnd("character",e-this.range.text.length);this.range.moveStart("character",
c)}else this.range.moveToElementText(a);else this.range.select();return this}})();var l=function(a,b){for(var c,d=0;a[d];d++)if(c=a[d],3===c.nodeType||4===c.nodeType){if(!1===b(c))return!1}else if(8!==c.nodeType&&!1===l(c.childNodes,b))return!1},n=function(a){return 3===a.nodeType||4===a.nodeType},u=function(a,b){return function(c,d){if(c[a]&&!d)return n(c[a])?c[a]:arguments.callee(c[a]);if(c[b])return n(c[b])?c[b]:arguments.callee(c[b]);if(c.parentNode)return arguments.callee(c.parentNode,!0)}},
v=u("firstChild","nextSibling"),w=u("lastChild","previousSibling"),t=function(a,b,c){return n(a)?q(a,b+c):a.childNodes[b]?q(a.childNodes[b],c):q(a.lastChild,c,!0)},q=function(a,b){var c=0>b?w:v,b=Math.abs(b);for(n(a)||(a=c(a));a&&b>=a.nodeValue.length;)hasMany=b-a.nodeValue.length,a=c(a);return{node:a,offset:c===v?b:a.nodeValue.length-b}},m=function(a,b){return a.left<=b.clientX&&a.left+a.width>=b.clientX&&a.top<=b.clientY&&a.top+a.height>=b.clientY},p=function(a){a=a||window;doc=a.document.documentElement;
body=a.document.body;return{left:(doc&&doc.scrollLeft||body&&body.scrollLeft||0)+(doc.clientLeft||0),top:(doc&&doc.scrollTop||body&&body.scrollTop||0)+(doc.clientTop||0)}};s=!!e.Range().range.moveToPoint})(o)});
