define(function(){return function(m){m.add("effect",function(b,o){var f=b.DOM,k=b.Anim,c=b.Switchable,d;b.mix(c.Config,{effect:"none",duration:0.5,easing:"easeNone",nativeAnim:!0});c.Effects={none:function(a,b,c){f.css(a,"display","none");f.css(b,"display","block");c()},fade:function(a,c,l){1!==a.length&&b.error("fade effect only supports steps == 1.");var g=this,h=g.config,e=a[0],d=c[0];g.anim&&g.anim.stop(!0);f.css(d,"opacity",1);g.anim=(new k(e,{opacity:0},h.duration,h.easing,function(){g.anim=
o;f.css(d,"z-index",9);f.css(e,"z-index",1);l()},h.nativeAnim)).run()},scroll:function(a,b,c,g){var h=this,a=h.config,b="scrollx"===a.effect,e={};e[b?"left":"top"]=-(h.viewSize[b?0:1]*g)+"px";h.anim&&h.anim.stop();h.anim=(new k(h.content,e,a.duration,a.easing,function(){h.anim=o;c()},a.nativeAnim)).run()}};d=c.Effects;d.scrollx=d.scrolly=d.scroll;c.Plugins.push({name:"effect",init:function(a){var c=a.config,d=c.effect,g=a.panels,h=a.content,e=c.steps,k=a.activeIndex,q=g.length;a.viewSize=[c.viewSize[0]||
g[0].offsetWidth*e,c.viewSize[1]||g[0].offsetHeight*e];if("none"!==d)switch(b.each(g,function(a){f.css(a,"display","block")}),d){case "scrollx":case "scrolly":f.css(h,"position","absolute");f.css(h.parentNode,"position","relative");"scrollx"===d&&(f.css(g,"float","left"),f.width(h,a.viewSize[0]*(q/e)));break;case "fade":var i=k*e,j=i+e-1,p;b.each(g,function(a,b){p=b>=i&&b<=j;f.css(a,{opacity:p?1:0,position:"absolute",zIndex:p?9:1})})}}});b.augment(c,{_switchView:function(a,c,f,g){var h=this,e=h.config.effect;
(b.isFunction(e)?e:d[e]).call(h,a,c,function(){h._fireOnSwitch(f)},f,g)}})},{host:"switchable"});m.add("autoplay",function(b,o){var f=b.Event,k=b.Switchable;b.mix(k.Config,{autoplay:!1,interval:5,pauseOnHover:!0});k.Plugins.push({name:"autoplay",init:function(c){function d(){l=b.later(function(){c.paused||c.switchTo(c.activeIndex<c.length-1?c.activeIndex+1:0,"forward")},k,!0)}var a=c.config,k=1E3*a.interval,l;a.autoplay&&(a.pauseOnHover&&(f.on(c.container,"mouseenter",function(){c.stop();c.paused=
!0}),f.on(c.container,"mouseleave",function(){c.paused=!1;d()})),d(),c.stop=function(){l&&(l.cancel(),l=o)})}})},{host:"switchable"});m.add("circular",function(b,o){function f(a,d,h,f,j){var n=this,a=n.config,d=n.length,s=n.activeIndex,r=a.scrollType===i,m=r?l:g,u=n.viewSize[r?0:1],r=-u*f,w={},x,v=j===q;(x=v&&0===s&&f===d-1||j===t&&s===d-1&&0===f)&&(r=k.call(n,n.panels,f,v,m,u));w[m]=r+e;n.anim&&n.anim.stop();n.anim=(new b.Anim(n.content,w,a.duration,a.easing,function(){x&&c.call(n,n.panels,f,v,m,
u);n.anim=o;h()},a.nativeAnim)).run()}function k(b,c,f,h,g){for(var e=this.config.steps,c=this.length,j=f?c-1:0,i=(j+1)*e,e=j*e;e<i;e++)d.css(b[e],a,s),d.css(b[e],h,(f?-1:1)*g*c);return f?g:-g*c}function c(b,c,e,f,g){for(var j=this.config.steps,c=this.length,i=e?c-1:0,k=(i+1)*j,j=i*j;j<k;j++)d.css(b[j],a,h),d.css(b[j],f,h);d.css(this.content,f,e?-g*(c-1):h)}var d=b.DOM,a="position",s="relative",l="left",g="top",h="",e="px",t="forward",q="backward",i="scrollx",j=b.Switchable;b.mix(j.Config,{circular:!1});
j.Plugins.push({name:"circular",init:function(a){a=a.config;if(a.circular&&(a.effect===i||"scrolly"===a.effect))a.scrollType=a.effect,a.effect=f}})},{host:"switchable"});m.add("lazyload",function(b){var o=b.DOM,f="beforeSwitch",k="img-src",c="area-data",d={},a=b.Switchable;d[k]="data-ks-lazyload-custom";d[c]="ks-datalazyload-custom";b.mix(a.Config,{lazyDataType:c});a.Plugins.push({name:"lazyload",init:function(a){function l(d){var i=h.steps,d=d.toIndex*i;g.loadCustomLazyData(a.panels.slice(d,d+i),
e);a:{var j,p;if(d=(i=e===k)?"img":e===c?"textarea":""){d=b.query(d,a.container);for(j=0,p=d.length;j<p;j++)if(i?o.attr(d[j],m):o.hasClass(d[j],m)){i=!1;break a}}i=!0}i&&a.detach(f,l)}var g=b.DataLazyload,h=a.config,e=h.lazyDataType,m=d[e];if(g&&e&&m)a.on(f,l)}})},{host:"switchable"});m.add("countdown",function(b,m){var f=b.DOM,k=b.Event,c=b.Anim,d=b.Switchable;b.mix(d.Config,{countdown:!1,countdownFromStyle:"",countdownToStyle:"width: 0"});d.Plugins.push({name:"countdown",init:function(a){function d(){l();
i=(new c(e[a.activeIndex],q,h-1)).run()}function l(){i&&(i.stop(),i=m)}var g=a.config,h=g.interval,e=[],t=g.countdownFromStyle,q=g.countdownToStyle,i;g.autoplay&&g.hasTriggers&&g.countdown&&(b.each(a.triggers,function(a,c){a.innerHTML='<div class="ks-switchable-trigger-mask"></div><div class="ks-switchable-trigger-content">'+a.innerHTML+"</div>";e[c]=a.firstChild}),g.pauseOnHover&&(k.on(a.container,"mouseenter",function(){l();var b=e[a.activeIndex];t?i=(new c(b,t,0.2,"easeOut")).run():f.removeAttr(b,
"style")}),k.on(a.container,"mouseleave",function(){l();f.removeAttr(e[a.activeIndex],"style");b.later(d,200)})),a.on("beforeSwitch",function(){l();f.removeAttr(e[a.activeIndex],"style")}),a.on("switch",function(){a.paused||d()}),d(a.activeIndex))}})},{requires:"switchable"})}});
