define(function(l){return function(i){i.add("switchable",function(b,d){function e(a,c){c=c||{};"markupType"in c||(c.panelCls?c.markupType=1:c.panels&&(c.markupType=2));c=b.merge(e.Config,c);this.container=b.get(a);this.config=c;this.activeIndex=c.activeIndex;this._init()}var f=b.DOM,g=b.Event;e.Config={markupType:0,navCls:"ks-switchable-nav",contentCls:"ks-switchable-content",triggerCls:"ks-switchable-trigger",panelCls:"ks-switchable-panel",triggers:[],panels:[],hasTriggers:!0,triggerType:"mouse",
delay:0.1,activeIndex:0,activeTriggerCls:"ks-active",steps:1,viewSize:[]};e.Plugins=[];b.augment(e,b.EventTarget,{_init:function(){var a=this,c=a.config;a._parseMarkup();c.switchTo&&a.switchTo(c.switchTo);c.hasTriggers&&a._bindTriggers();b.each(e.Plugins,function(c){c.init&&c.init(a)});a.fire("init")},_parseMarkup:function(){var a=this.container,c=this.config,j,h=[],d=[];switch(c.markupType){case 0:(j=b.get("."+c.navCls,a))&&(h=f.children(j));j=b.get("."+c.contentCls,a);d=f.children(j);break;case 1:h=
b.query("."+c.triggerCls,a);d=b.query("."+c.panelCls,a);break;case 2:h=c.triggers,d=c.panels}a=d.length;this.length=a/c.steps;c.hasTriggers&&0<a&&0===h.length&&(h=this._generateTriggersMarkup(this.length));this.triggers=b.makeArray(h);this.panels=b.makeArray(d);this.content=j||d[0].parentNode},_generateTriggersMarkup:function(a){var c=this.config,b=f.create("<ul>"),d,e;b.className=c.navCls;for(e=0;e<a;e++)d=f.create("<li>"),e===this.activeIndex&&(d.className=c.activeTriggerCls),d.innerHTML=e+1,b.appendChild(d);
this.container.appendChild(b);return f.children(b)},_bindTriggers:function(){var a=this,c=a.config,b=a.triggers,d,e,k=b.length;for(e=0;e<k;e++)(function(e){d=b[e];g.on(d,"click",function(){a._onFocusTrigger(e)});"mouse"===c.triggerType&&(g.on(d,"mouseenter",function(){a._onMouseEnterTrigger(e)}),g.on(d,"mouseleave",function(){a._onMouseLeaveTrigger(e)}))})(e)},_onFocusTrigger:function(a){this._triggerIsValid(a)&&(this._cancelSwitchTimer(),this.switchTo(a))},_onMouseEnterTrigger:function(a){var c=
this;c._triggerIsValid(a)&&(c.switchTimer=b.later(function(){c.switchTo(a)},1E3*c.config.delay))},_onMouseLeaveTrigger:function(){this._cancelSwitchTimer()},_triggerIsValid:function(a){return this.activeIndex!==a},_cancelSwitchTimer:function(){this.switchTimer&&(this.switchTimer.cancel(),this.switchTimer=d)},switchTo:function(a,c){var b=this.config,e=this.triggers,f=this.panels,k=this.activeIndex,g=b.steps,m=k*g,n=a*g;if(!this._triggerIsValid(a)||!1===this.fire("beforeSwitch",{toIndex:a}))return this;
b.hasTriggers&&this._switchTrigger(-1<k?e[k]:null,e[a]);c===d&&(c=a>k?"forward":"backward");this._switchView(f.slice(m,m+g),f.slice(n,n+g),a,c);this.activeIndex=a;return this},_switchTrigger:function(a,c){var b=this.config.activeTriggerCls;a&&f.removeClass(a,b);f.addClass(c,b)},_switchView:function(a,b,d){f.css(a,"display","none");f.css(b,"display","block");this._fireOnSwitch(d)},_fireOnSwitch:function(a){this.fire("switch",{currentIndex:a})},prev:function(){var a=this.activeIndex;this.switchTo(0<
a?a-1:this.length-1,"backward")},next:function(){var a=this.activeIndex;this.switchTo(a<this.length-1?a+1:0,"forward")}});b.Switchable=e},{requires:["core"]});l("./ks_datalazyload")(i);l("./ks_swich_effect")(i);i.add("tabs",function(b){function d(b,f){if(!(this instanceof d))return new d(b,f);d.superclass.constructor.call(this,b,f)}b.extend(d,b.Switchable);b.Tabs=d},{host:"switchable"});i.add("slide",function(b){function d(f,g){if(!(this instanceof d))return new d(f,g);d.superclass.constructor.call(this,
f,b.merge(e,g))}var e={autoplay:!0,circular:!0};b.extend(d,b.Switchable);b.Slide=d},{host:"switchable"});i.add("carousel",function(b,d){function e(a,c){var d=this;if(!(d instanceof e))return new e(a,c);d.on("init",function(){f(d)});e.superclass.constructor.call(d,a,b.merge(i,c))}function f(e){var f=e.config,i=f.disableBtnCls;b.each(["prev","next"],function(d){var h=e[d+"Btn"]=b.get(c+f[d+"BtnCls"],e.container);a.on(h,"click",function(a){a.preventDefault();if(!g.hasClass(h,i))e[d]()})});if(!f.circular)e.on("switch",
function(a){a=a.currentIndex;a=0===a?e[j]:a===e.length-1?e[h]:d;g.removeClass([e[j],e[h]],i);a&&g.addClass(a,i)});a.on(e.panels,"click focus",function(){e.fire("itemSelected",{item:this})})}var g=b.DOM,a=b.Event,c=".",j="prevBtn",h="nextBtn",i={circular:!0,prevBtnCls:"ks-switchable-prev-btn",nextBtnCls:"ks-switchable-next-btn",disableBtnCls:"ks-switchable-disable-btn"};b.extend(e,b.Switchable);b.Carousel=e},{host:"switchable"});i.add("accordion",function(b){function d(e,a){if(!(this instanceof d))return new d(e,
a);d.superclass.constructor.call(this,e,b.merge(f,a));this.config.multiple&&(this._switchTrigger=function(){})}var e=b.DOM,f={markupType:1,triggerType:"click",multiple:!1};b.extend(d,b.Switchable);b.Accordion=d;b.augment(d,{_triggerIsValid:function(b){return this.activeIndex!==b||this.config.multiple},_switchView:function(b,a,c){var f=this.config,h=a[0];f.multiple?(e.toggleClass(this.triggers[c],f.activeTriggerCls),e.css(h,"display","none"==h.style.display?"block":"none"),this._fireOnSwitch(c)):d.superclass._switchView.call(this,
b,a,c)}})},{host:"switchable"})}});
