define(function(){return function(n){(function(b){var j=[],o=/^url\(["']?([^"'\)]*)["']?\);?$/i,p=/\.png$/i,m=b.browser.msie&&6==b.browser.version;b(window).resize(function(){b.each(j,function(){this.refresh(!0)})});b.Poshytip=function(a,f){this.$elm=b(a);this.opts=b.extend({},b.fn.poshytip.defaults,f);this.$tip=b(['<div class="',this.opts.className,'"><div class="tip-inner tip-bg-image"></div><div class="tip-arrow tip-arrow-top tip-arrow-right tip-arrow-bottom tip-arrow-left"></div></div>'].join("")).appendTo(document.body);
this.$arrow=this.$tip.find("div.tip-arrow");this.$inner=this.$tip.find("div.tip-inner");this.disabled=!1;this.content=null;this.init()};b.Poshytip.prototype={init:function(){j.push(this);var a=this.$elm.attr("title");this.$elm.data("title.poshytip",void 0!==a?a:null).data("poshytip",this);if("none"!=this.opts.showOn)switch(this.$elm.bind({"mouseenter.poshytip":b.proxy(this.mouseenter,this),"mouseleave.poshytip":b.proxy(this.mouseleave,this)}),this.opts.showOn){case "hover":"cursor"==this.opts.alignTo&&
this.$elm.bind("mousemove.poshytip",b.proxy(this.mousemove,this));this.opts.allowTipHover&&this.$tip.hover(b.proxy(this.clearTimeouts,this),b.proxy(this.mouseleave,this));break;case "focus":this.$elm.bind({"focus.poshytip":b.proxy(this.show,this),"blur.poshytip":b.proxy(this.hide,this)})}},mouseenter:function(){if(this.disabled)return!0;this.$elm.attr("title","");if("focus"==this.opts.showOn)return!0;this.clearTimeouts();this.showTimeout=setTimeout(b.proxy(this.show,this),this.opts.showTimeout)},
mouseleave:function(a){if(this.disabled||this.asyncAnimating&&(this.$tip[0]===a.relatedTarget||n.contains(this.$tip[0],a.relatedTarget)))return!0;a=this.$elm.data("title.poshytip");null!==a&&this.$elm.attr("title",a);if("focus"==this.opts.showOn)return!0;this.clearTimeouts();this.hideTimeout=setTimeout(b.proxy(this.hide,this),this.opts.hideTimeout)},mousemove:function(a){if(this.disabled)return!0;this.eventX=a.pageX;this.eventY=a.pageY;this.opts.followCursor&&this.$tip.data("active")&&(this.calcPos(),
this.$tip.css({left:this.pos.l,top:this.pos.t}),this.pos.arrow&&(this.$arrow[0].className="tip-arrow tip-arrow-"+this.pos.arrow))},show:function(){!this.disabled&&!this.$tip.data("active")&&(this.reset(),this.update(),this.display(),this.opts.timeOnScreen&&setTimeout(b.proxy(this.hide,this),this.opts.timeOnScreen))},hide:function(){!this.disabled&&this.$tip.data("active")&&this.display(!0)},reset:function(){this.$tip.queue([]).detach().css("visibility","hidden").data("active",!1);this.$inner.find("*").poshytip("hide");
this.opts.fade&&this.$tip.css("opacity",this.opacity);this.$arrow[0].className="tip-arrow tip-arrow-top tip-arrow-right tip-arrow-bottom tip-arrow-left";this.asyncAnimating=!1},update:function(a,b){if(!this.disabled){var d=void 0!==a;if(d){if(b||(this.opts.content=a),!this.$tip.data("active"))return}else a=this.opts.content;var c=this,e="function"==typeof a?a.call(this.$elm[0],function(a){c.update(a)}):"[title]"==a?this.$elm.data("title.poshytip"):a;this.content!==e&&(this.$inner.empty().append(e),
this.content=e);this.refresh(d)}},refresh:function(a){if(!this.disabled){if(a){if(!this.$tip.data("active"))return;var f={left:this.$tip.css("left"),top:this.$tip.css("top")}}this.$tip.css({left:0,top:0}).appendTo(document.body);void 0===this.opacity&&(this.opacity=this.$tip.css("opacity"));var d=this.$tip.css("background-image").match(o),c=this.$arrow.css("background-image").match(o);if(d){var e=p.test(d[1]);m&&e?(this.$tip.css("background-image","none"),this.$inner.css({margin:0,border:0,padding:0}),
d=e=!1):this.$tip.prepend('<table border="0" cellpadding="0" cellspacing="0"><tr><td class="tip-top tip-bg-image" colspan="2"><span></span></td><td class="tip-right tip-bg-image" rowspan="2"><span></span></td></tr><tr><td class="tip-left tip-bg-image" rowspan="2"><span></span></td><td></td></tr><tr><td class="tip-bottom tip-bg-image" colspan="2"><span></span></td></tr></table>').css({border:0,padding:0,"background-image":"none","background-color":"transparent"}).find(".tip-bg-image").css("background-image",
'url("'+d[1]+'")').end().find("td").eq(3).append(this.$inner);e&&!b.support.opacity&&(this.opts.fade=!1)}c&&!b.support.opacity&&(m&&p.test(c[1])&&(c=!1,this.$arrow.css("background-image","none")),this.opts.fade=!1);d=this.$tip.find("table");if(m){this.$tip[0].style.width="";d.width("auto").find("td").eq(3).width("auto");var e=this.$tip.width(),g=parseInt(this.$tip.css("min-width")),h=parseInt(this.$tip.css("max-width"));!isNaN(g)&&e<g?e=g:!isNaN(h)&&e>h&&(e=h);this.$tip.add(d).width(e).eq(0).find("td").eq(3).width("100%")}else d[0]&&
d.width("auto").find("td").eq(3).width("auto").end().end().width(document.defaultView&&document.defaultView.getComputedStyle&&parseFloat(document.defaultView.getComputedStyle(this.$tip[0],null).width)||this.$tip.width()).find("td").eq(3).width("100%");this.tipOuterW=this.$tip.outerWidth();this.tipOuterH=this.$tip.outerHeight();this.calcPos();c&&this.pos.arrow&&(this.$arrow[0].className="tip-arrow tip-arrow-"+this.pos.arrow,this.$arrow.css("visibility","inherit"));if(a){this.asyncAnimating=!0;var i=
this;this.$tip.css(f).animate({left:this.pos.l,top:this.pos.t},200,function(){i.asyncAnimating=!1})}else this.$tip.css({left:this.pos.l,top:this.pos.t})}},display:function(a){var f=this.$tip.data("active");if(!(f&&!a||!f&&a)){this.$tip.stop();if((this.opts.slide&&this.pos.arrow||this.opts.fade)&&(a&&this.opts.hideAniDuration||!a&&this.opts.showAniDuration)){var d={},c={};if(this.opts.slide&&this.pos.arrow){var e,g;"bottom"==this.pos.arrow||"top"==this.pos.arrow?(e="top",g="bottom"):(e="left",g="right");
var h=parseInt(this.$tip.css(e));d[e]=h+(a?0:this.pos.arrow==g?-this.opts.slideOffset:this.opts.slideOffset);c[e]=h+(a?this.pos.arrow==g?this.opts.slideOffset:-this.opts.slideOffset:0)+"px"}this.opts.fade&&(d.opacity=a?this.$tip.css("opacity"):0,c.opacity=a?0:this.opacity);this.$tip.css(d).animate(c,this.opts[a?"hideAniDuration":"showAniDuration"])}a?this.$tip.queue(b.proxy(this.reset,this)):this.$tip.css("visibility","inherit");this.$tip.data("active",!f)}},disable:function(){this.reset();this.disabled=
!0},enable:function(){this.disabled=!1},destroy:function(){this.reset();this.$tip.remove();delete this.$tip;this.content=null;this.$elm.unbind(".poshytip").removeData("title.poshytip").removeData("poshytip");j.splice(b.inArray(this,j),1)},clearTimeouts:function(){this.showTimeout&&(clearTimeout(this.showTimeout),this.showTimeout=0);this.hideTimeout&&(clearTimeout(this.hideTimeout),this.hideTimeout=0)},calcPos:function(){var a={l:0,t:0,arrow:""},f=b(window),d=f.scrollLeft(),c=f.scrollTop(),e=f.width(),
f=f.height(),g,h,i,k,j,l;"cursor"==this.opts.alignTo?(g=h=i=this.eventX,k=j=l=this.eventY):(h=this.$elm.offset(),g=h.left,k=h.top,i=this.$elm.outerWidth(),l=this.$elm.outerHeight(),g+="inner-right"!=this.opts.alignX?0:i,h=g+Math.floor(i/2),i=g+("inner-left"!=this.opts.alignX?i:0),k+="inner-bottom"!=this.opts.alignY?0:l,j=k+Math.floor(l/2),l=k+("inner-top"!=this.opts.alignY?l:0));switch(this.opts.alignX){case "right":case "inner-left":a.l=i+this.opts.offsetX;a.l+this.tipOuterW>d+e&&(a.l=d+e-this.tipOuterW);
if("right"==this.opts.alignX||"center"==this.opts.alignY)a.arrow="left";break;case "center":a.l=h-Math.floor(this.tipOuterW/2);a.l+this.tipOuterW>d+e?a.l=d+e-this.tipOuterW:a.l<d&&(a.l=d);break;default:if(a.l=g-this.tipOuterW-this.opts.offsetX,a.l<d&&(a.l=d),"left"==this.opts.alignX||"center"==this.opts.alignY)a.arrow="right"}switch(this.opts.alignY){case "bottom":case "inner-top":a.t=l+this.opts.offsetY;if(!a.arrow||"cursor"==this.opts.alignTo)a.arrow="top";a.t+this.tipOuterH>c+f&&(a.t=k-this.tipOuterH-
this.opts.offsetY,"top"==a.arrow&&(a.arrow="bottom"));break;case "center":a.t=j-Math.floor(this.tipOuterH/2);a.t+this.tipOuterH>c+f?a.t=c+f-this.tipOuterH:a.t<c&&(a.t=c);break;default:a.t=k-this.tipOuterH-this.opts.offsetY;if(!a.arrow||"cursor"==this.opts.alignTo)a.arrow="bottom";a.t<c&&(a.t=l+this.opts.offsetY,"bottom"==a.arrow&&(a.arrow="top"))}this.pos=a}};b.fn.poshytip=function(a){if("string"==typeof a){var f=arguments,d=a;Array.prototype.shift.call(f);"destroy"==d&&this.die("mouseenter.poshytip").die("focus.poshytip");
return this.each(function(){var a=b(this).data("poshytip");a&&a[d]&&a[d].apply(a,f)})}var c=b.extend({},b.fn.poshytip.defaults,a);b("#poshytip-css-"+c.className)[0]||b(['<style id="poshytip-css-',c.className,'" type="text/css">div.',c.className,"{visibility:hidden;position:absolute;top:0;left:0;}div.",c.className," table, div.",c.className," td{margin:0;font-family:inherit;font-size:inherit;font-weight:inherit;font-style:inherit;font-variant:inherit;}div.",c.className," td.tip-bg-image span{display:block;font:1px/1px sans-serif;height:",
c.bgImageFrameSize,"px;width:",c.bgImageFrameSize,"px;overflow:hidden;}div.",c.className," td.tip-right{background-position:100% 0;}div.",c.className," td.tip-bottom{background-position:100% 100%;}div.",c.className," td.tip-left{background-position:0 100%;}div.",c.className," div.tip-inner{background-position:-",c.bgImageFrameSize,"px -",c.bgImageFrameSize,"px;}div.",c.className," div.tip-arrow{visibility:hidden;position:absolute;overflow:hidden;font:1px/1px sans-serif;}</style>"].join("")).appendTo("head");
if(c.liveEvents&&"none"!=c.showOn){var e=b.extend({},c,{liveEvents:!1});switch(c.showOn){case "hover":this.live("mouseenter.poshytip",function(){var a=b(this);a.data("poshytip")||a.poshytip(e).poshytip("mouseenter")});break;case "focus":this.live("focus.poshytip",function(){var a=b(this);a.data("poshytip")||a.poshytip(e).poshytip("show")})}return this}return this.each(function(){new b.Poshytip(this,c)})};b.fn.poshytip.defaults={content:"[title]",className:"tip-yellow",bgImageFrameSize:10,showTimeout:500,
hideTimeout:100,timeOnScreen:0,showOn:"hover",liveEvents:!1,alignTo:"cursor",alignX:"right",alignY:"top",offsetX:-22,offsetY:18,allowTipHover:!0,followCursor:!1,fade:!0,slide:!0,slideOffset:8,showAniDuration:300,hideAniDuration:300}})(n)}});
