define(function(){return function(u){(function(c){c.fn.paginate=function(a){var d=c.extend({},c.fn.paginate.defaults,a);return this.each(function(){$this=c(this);var a=c.meta?c.extend({},d,$this.data()):d;c.fn.draw(a,$this,a.start)})};var n=0,m=0;if(0<navigator.appVersion.indexOf("MSIE 7.0"))var q="ie7";c.fn.paginate.defaults={count:5,start:12,display:5,border:!0,border_color:"#fff",text_color:"#8cc59d",background_color:"black",border_hover_color:"#fff",text_hover_color:"#fff",background_hover_color:"#fff",
rotate:!0,images:!0,mouse:"slide",onChange:function(){return!1}};c.fn.draw=function(a,d,i){a.display>a.count&&(a.display=a.count);$this.empty();if(a.images)var h="jPag-sprevious-img",d="jPag-snext-img";else h="jPag-sprevious",d="jPag-snext";var g=c(document.createElement("a")).addClass("jPag-first").html("First");if(a.rotate)var e=a.images?c(document.createElement("span")).addClass(h):c(document.createElement("span")).addClass(h).html("&laquo;");h=c(document.createElement("div")).addClass("jPag-control-back");
h.append(g).append(e);for(var b=c(document.createElement("div")).css("overflow","hidden"),o=c(document.createElement("ul")).addClass("jPag-pages"),p,r=0;r<a.count;r++){var j=r+1;j==i?p=j=c(document.createElement("li")).html('<span class="jPag-current">'+j+"</span>"):j=c(document.createElement("li")).html("<a>"+j+"</a>");o.append(j)}b.append(o);if(a.rotate)var f=a.images?c(document.createElement("span")).addClass(d):c(document.createElement("span")).addClass(d).html("&raquo;");var i=c(document.createElement("a")).addClass("jPag-last").html("Last"),
k=c(document.createElement("div")).addClass("jPag-control-front");k.append(f).append(i);$this.addClass("jPaginate").append(h).append(b).append(k);if(a.border)s="none"==a.background_color?{color:a.text_color,border:"1px solid "+a.border_color}:{color:a.text_color,"background-color":a.background_color,border:"1px solid "+a.border_color},t="none"==a.background_hover_color?{color:a.text_hover_color,border:"1px solid "+a.border_hover_color}:{color:a.text_hover_color,"background-color":a.background_hover_color,
border:"1px solid "+a.border_hover_color};else var s="none"==a.background_color?{color:a.text_color}:{color:a.text_color,"background-color":a.background_color},t="none"==a.background_hover_color?{color:a.text_hover_color}:{color:a.text_hover_color,"background-color":a.background_hover_color};c.fn.applystyle(a,$this,s,t,g,o,b,k);var l=n-g.parent().width()-3;"ie7"==q?(b.css("width",l+72+"px"),k.css("left",n+6+72+"px")):(b.css("width",l+"px"),k.css("left",n+6+"px"));a.rotate&&(f.hover(function(){thumbs_scroll_interval=
setInterval(function(){var a=b.scrollLeft()+1;b.scrollLeft(a)},20)},function(){clearInterval(thumbs_scroll_interval)}),e.hover(function(){thumbs_scroll_interval=setInterval(function(){var a=b.scrollLeft()-1;b.scrollLeft(a)},20)},function(){clearInterval(thumbs_scroll_interval)}),"press"==a.mouse?(f.mousedown(function(){thumbs_mouse_interval=setInterval(function(){var a=b.scrollLeft()+5;b.scrollLeft(a)},20)}).mouseup(function(){clearInterval(thumbs_mouse_interval)}),e.mousedown(function(){thumbs_mouse_interval=
setInterval(function(){var a=b.scrollLeft()-5;b.scrollLeft(a)},20)}).mouseup(function(){clearInterval(thumbs_mouse_interval)})):(e.click(function(){var a=l-10,a=b.scrollLeft()-a;b.animate({scrollLeft:a+"px"})}),f.click(function(){var a=l-10,a=b.scrollLeft()+a;b.animate({scrollLeft:a+"px"})})));g.click(function(){b.animate({scrollLeft:"0px"});b.find("li").eq(0).click()});i.click(function(){b.animate({scrollLeft:m+"px"});b.find("li").eq(a.count-1).click()});b.find("li").click(function(){p.html("<a>"+
p.find(".jPag-current").html()+"</a>");var d=c(this).find("a").html();c(this).html('<span class="jPag-current">'+d+"</span>");p=c(this);c.fn.applystyle(a,c(this).parent().parent().parent(),s,t,g,o,b,k);var e=this.offsetLeft/2;b.scrollLeft();var f=e-l/2;"ie7"==q?b.animate({scrollLeft:e+f-g.parent().width()+52+"px"}):b.animate({scrollLeft:e+f-g.parent().width()+"px"});a.onChange(d)});f=b.find("li").eq(a.start-1);f.attr("id","tmp");e=document.getElementById("tmp").offsetLeft/2;f.removeAttr("id");f=e-
l/2;"ie7"==q?b.animate({scrollLeft:e+f-g.parent().width()+52+"px"}):b.animate({scrollLeft:e+f-g.parent().width()+"px"})};c.fn.applystyle=function(a,d,i,h,g,e){d.find("a").css(i);d.find("span.jPag-current").css(h);d.find("a").hover(function(){c(this).css(h)},function(){c(this).css(i)});d.css("padding-left",g.parent().width()+5+"px");m=0;d.find("li").each(function(b){b==a.display-1&&(n=this.offsetLeft+this.offsetWidth);m+=this.offsetWidth});e.css("width",m+"px")}})(u)}});
