define(function(){return function(b){var x,u,y={hintText:"输入查找字符 ...",noResultsText:"未有结果",searchingText:"查找中 ...",deleteText:"&times;",searchDelay:300,minChars:1,tokenLimit:null,jsonContainer:null,method:"GET",contentType:"json",queryParam:"q",tokenDelimiter:",",preventDuplicates:!1,prePopulate:null,animateDropdown:!0,onResult:null,onAdd:null,onDelete:null},z={tokenList:"token-input-list",token:"token-input-token",tokenDelete:"token-input-delete-token",selectedToken:"token-input-selected-token",
highlightedToken:"token-input-highlighted-token",dropdown:"token-input-dropdown",dropdownItem:"token-input-dropdown-item",dropdownItem2:"token-input-dropdown-item2",selectedDropdownItem:"token-input-selected-dropdown-item",inputToken:"token-input-input-token"};x=0;u=1;b.fn.tokenInput=function(r,i){var a=b.extend({},y,i||{});return this.each(function(){new b.TokenList(this,r,a)})};b.TokenList=function(r,i,a){function k(c,d){var e=b("<li><p>"+d+"</p> </li>").addClass(a.classes.token).insertBefore(j);
b("<span>"+a.deleteText+"</span>").addClass(a.classes.tokenDelete).appendTo(e).click(function(){D(b(this).parent());return!1});var v={id:c,name:d};b.data(e.get(0),"tokeninput",v);s.push(v);v=b.map(s,function(a){return a.id});t.val(v.join(a.tokenDelimiter));l+=1;return e}function E(c){var d=b.data(c.get(0),"tokeninput"),c=a.onAdd;if(0<l&&a.preventDuplicates){var e=null;p.children().each(function(){var a=b(this),c=b.data(a.get(0),"tokeninput");if(c&&c.id===d.id)return e=a,!1});if(e){m(e);j.insertAfter(e);
f.focus();return}}k(d.id,d.name);null!==a.tokenLimit&&l>=a.tokenLimit?(f.hide(),n()):(f.focus(),f.val(""),n(),b.isFunction(c)&&c(d))}function m(c){c.addClass(a.classes.selectedToken);g=c.get(0);f.val("");n()}function q(c,b){c.removeClass(a.classes.selectedToken);g=null;b===x?j.insertBefore(c):b===u?j.insertAfter(c):j.appendTo(p);f.focus()}function D(c){var d=b.data(c.get(0),"tokeninput"),e=a.onDelete;c.remove();g=null;f.focus();s=b.grep(s,function(a){return a.id!==d.id});c=b.map(s,function(a){return a.id});
t.val(c.join(a.tokenDelimiter));l-=1;null!==a.tokenLimit&&f.show().val("").focus();b.isFunction(e)&&e(d)}function n(){o.hide().empty();h=null}function w(){o.css({position:"absolute",top:b(p).offset().top+b(p).outerHeight(),left:b(p).offset().left,zindex:999}).show()}function A(c,d){if(d&&d.length){o.empty();var e=b("<ul>").appendTo(o).mouseover(function(a){B(b(a.target).closest("li"))}).mousedown(function(a){E(b(a.target).closest("li"));return!1}).hide();b.each(d,function(d,f){var g=b("<li>"+f.name.replace(RegExp("(?![^&;]+;)(?!<[^<>]*)("+
c+")(?![^<>]*>)(?![^&;]+;)","gi"),"<b>$1</b>")+"</li>").appendTo(e);d%2?g.addClass(a.classes.dropdownItem):g.addClass(a.classes.dropdownItem2);0===d&&B(g);b.data(g.get(0),"tokeninput",{id:f.id,name:f.name})});w();a.animateDropdown?e.slideDown("fast"):e.show()}else a.noResultsText&&(o.html("<p>"+a.noResultsText+"</p>"),w())}function B(c){c&&(h&&(b(h).removeClass(a.classes.selectedDropdownItem),h=null),c.addClass(a.classes.selectedDropdownItem),h=c.get(0))}function F(){var c=f.val().toLowerCase();c&&
c.length&&(g&&q(b(g),u),c.length>=a.minChars?(a.searchingText&&(o.html("<p>"+a.searchingText+"</p>"),w()),clearTimeout(G),G=setTimeout(function(){y(c)},a.searchDelay)):n())}function y(c){var d=H.get(c);if(d)A(c,d);else if(a.url){var e={data:{}};-1<a.url.indexOf("?")?(d=a.url.split("?"),e.url=d[0],d=d[1].split("&"),b.each(d,function(a,c){var b=c.split("=");e.data[b[0]]=b[1]})):e.url=a.url;e.data[a.queryParam]=c;e.type=a.method;e.dataType=a.contentType;a.crossDomain&&(e.dataType="jsonp");e.success=
function(d){b.isFunction(a.onResult)&&(d=a.onResult.call(this,d));H.add(c,a.jsonContainer?d[a.jsonContainer]:d);f.val().toLowerCase()===c&&A(c,a.jsonContainer?d[a.jsonContainer]:d)};b.ajax(e)}else a.local_data&&(d=b.grep(a.local_data,function(a){return-1<a.value.toLowerCase().indexOf(c.toLowerCase())}),A(c,d))}"string"===b.type(i)?(a.url=i,void 0===a.crossDomain&&(a.crossDomain=-1===a.url.indexOf("://")?!1:location.href.split(/\/+/g)[1]!==a.url.split(/\/+/g)[1])):"array"===b.type(i)&&(a.local_data=
i);a.classes?a.classes=b.extend({},z,a.classes):a.theme?(a.classes={},b.each(z,function(c,b){a.classes[c]=b+"-"+a.theme})):a.classes=z;var s=[],l=0,H=new b.TokenList.Cache,G,C,f=b('<input type="text"  autocomplete="off">').css({outline:"none"}).focus(function(){if((null===a.tokenLimit||a.tokenLimit!==l)&&a.hintText)o.html("<p>"+a.hintText+"</p>"),w()}).blur(function(){n()}).bind("keyup keydown blur update",function(){if(C!==(C=f.val())){var a=C.replace(/&/g,"&amp;").replace(/\s/g," ").replace(/</g,
"&lt;").replace(/>/g,"&gt;");I.html(a);f.width(I.width()+30)}}).keydown(function(a){var d,e;switch(a.keyCode){case 37:case 39:case 38:case 40:if(b(this).val())return d=null,d=40===a.keyCode||39===a.keyCode?b(h).next():b(h).prev(),d.length&&B(d),!1;d=j.prev();e=j.next();d.length&&d.get(0)===g||e.length&&e.get(0)===g?37===a.keyCode||38===a.keyCode?q(b(g),x):q(b(g),u):(37===a.keyCode||38===a.keyCode)&&d.length?m(b(d.get(0))):(39===a.keyCode||40===a.keyCode)&&e.length&&m(b(e.get(0)));break;case 8:d=j.prev();
if(b(this).val().length)1===b(this).val().length?n():setTimeout(function(){F()},5);else return g?D(b(g)):d.length&&m(b(d.get(0))),!1;break;case 9:case 13:case 108:case 188:if(h)return E(b(h)),!1;break;case 27:return n(),!0;default:String.fromCharCode(a.which)&&setTimeout(function(){F()},5)}}),t=b(r).hide().val("").focus(function(){f.focus()}).blur(function(){f.blur()}),g=null,h=null,p=b("<ul />").addClass(a.classes.tokenList).click(function(a){if((a=b(a.target).closest("li"))&&a.get(0)&&b.data(a.get(0),
"tokeninput")){var d=g;g&&q(b(g),2);d===a.get(0)?q(a,2):m(a)}else g&&q(b(g),2),f.focus()}).mouseover(function(c){(c=b(c.target).closest("li"))&&g!==this&&c.addClass(a.classes.highlightedToken)}).mouseout(function(c){(c=b(c.target).closest("li"))&&g!==this&&c.removeClass(a.classes.highlightedToken)}).insertBefore(t),j=b("<li />").addClass(a.classes.inputToken).appendTo(p).append(f),o=b("<div>").addClass(a.classes.dropdown).appendTo("body").hide(),I=b("<tester/>").insertAfter(f).css({position:"absolute",
top:-9999,left:-9999,width:"auto",fontSize:f.css("fontSize"),fontFamily:f.css("fontFamily"),fontWeight:f.css("fontWeight"),letterSpacing:f.css("letterSpacing"),whiteSpace:"nowrap"});t.val("");(li_data=a.prePopulate||t.data("pre"))&&li_data.length&&b.each(li_data,function(a,b){k(b.id,b.name)})};b.TokenList.Cache=function(r){var i=b.extend({max_size:500},r),a={},k=0;this.add=function(b,m){k>i.max_size&&(a={},k=0);a[b]||(k+=1);a[b]=m};this.get=function(b){return a[b]}}}});
