(function(j){function f(a){if(!this.data)return new f(a);this._data=a;return this}function d(a,b){if(a&&b){for(var c=b.split("."),b=c.pop();a&&c.length;)a=a[c.shift()];return[a,b]}return[]}function a(b){if(!this.data)return new a(b);this._data=b;return this}function c(a){if("number"!==typeof a||0>a)throw"Invalid index.";}function b(a,b,c,e,d){var m=c[0];a._beforeChange&&a._beforeChange.call(a,m,e,d);(b=b(d))&&(d=b);a._afterChange&&a._afterChange.call(a,m,e,d);c.triggerHandler(e,d);a._afterEvent&&
a._afterEvent.call(a,m,e,d)}j.observable=function(b,c){var e=j.data(b,"__observableFactory__"),d=c&&!!c.useDefault;return e&&!d?e(b):j.isArray(b)?new a(b):new f(b)};j.observable.track=function(b,c){if(c&&j.data(b,"__observableFactory__"))throw"Observable already tracked for this data.";j.data(b,"__observableFactory__",!c?null:function(b){b=j.isArray(b)?new a(b):new f(b);b._beforeChange=c.beforeChange;b._afterChange=c.afterChange;b._afterEvent=c.afterEvent;return b})};var e=[].splice;j.observable.Object=
f;f.prototype={_data:null,data:function(){return this._data},setProperty:function(a,c){if(j.isArray(a))for(var e=0,h=a.length;e<h;e++){var l=a[e];this.setProperty(l.name,l.value)}else if("object"===typeof a)for(e in a)this.setProperty(e,a[e]);else{var m,e=this._data,f=d(e,a),a=f[1];if(f=f[0])h=f[a],j.isFunction(h)&&(m=h,h=h.call(f)),h={path:a,value:c},b(this,function(b){m?(m.call(f,c),b.value=m.call(f)):f[a]=c;return b},j(e),"propertyChange",h)}return this}};j.observable.Array=a;a.prototype={_data:null,
data:function(){return this._data},insert:function(a,b){c(a);if(1<arguments.length&&(b=j.isArray(b)?b:[b],0<b.length)){var d=this;this._changeDataAndTriggerEvents(function(){e.apply(d._data,[a,0].concat(b))},{change:"insert",index:a,items:b})}return this},remove:function(a,b){c(a);if(b=void 0===b||null===b?1:b){var e=this,d=this._data.slice(a,a+b);this._changeDataAndTriggerEvents(function(){e._data.splice(a,b)},{change:"remove",index:a,items:d})}return this},move:function(a,b,e){c(a);c(b);if(e=void 0===
e||null===e?1:e){var d=this,l=this._data.slice(a,a+e);this._changeDataAndTriggerEvents(function(){d._data.splice(a,e);d._data.splice.apply(d._data,[b,0].concat(l))},{change:"move",oldIndex:a,newIndex:b,items:l})}return this},refresh:function(a){var b=this;this._changeDataAndTriggerEvents(function(){b._data.splice.apply(b._data,[0,b._data.length].concat(a))},{change:"refresh",oldItems:this._data.slice(0),newItems:a});return this},_changeDataAndTriggerEvents:function(a,c){b(this,a,j([this._data]),"arrayChange",
c)}}})(jQuery);
(function(j){function f(a,b){for(var e in b)a[e]=b[e]}function d(a){for(var a=a.split("."),b=j,e=0;e<a.length;e++){var k=b[a[e]];if(!k||"object"!==typeof k)b[a[e]]=k={};b=k}return b}var a=d("Microsoft.ServiceModel.DomainServices");a.defineNamespace=d;a.defineClass=function(a,b,e){a=a||function(){};b&&f(a.prototype,b);e&&f(a,e);return a};a.deriveClass=function(a,b,e,k){var d=a.prototype,i={};f(i,d);if(e)for(var h in e)i[h]="function"===typeof e[h]&&"function"===typeof d[h]?function(a,b){return function(){var a=
this._super;this._super=d;var c=b.apply(this,arguments);this._super=a;return c}}(h,e[h]):e[h];b=b?function(a){return function(){var b=this._super;this._super=d;a.apply(this,arguments);this._super=b}}(b):function(){};b.prototype=i;b.prototype.constructor=b;f(b,a);k&&f(b,k);return b}})(this);
(function(j,f){f.defineNamespace("Microsoft.ServiceModel.DomainServices.Observability").Configuration={track:function(d,a){a?$.observable.track(d,{beforeChange:a.beforeChange,afterChange:a.afterChange,afterEvent:a.afterEvent}):$.observable.track(d,null)},createInsertDeferredEvent:function(d,a,c){return function(){var b={change:"insert",index:a,items:c};$([d]).triggerHandler("arrayChange",b)}},createRemoveDeferredEvent:function(d,a,c){return function(){var b={change:"remove",index:a,items:c};$([d]).triggerHandler("arrayChange",
b)}},createRefreshDeferredEvent:function(d,a,c){return function(){var b={change:"refresh",oldItems:a,newItems:c};$([d]).triggerHandler("arrayChange",b)}},createSetPropertyDeferredEvent:function(d,a,c,b){return function(){var c={path:a,value:b};$(d).triggerHandler("propertyChange",c)}},observableInsert:function(d,a,c){$.observable(d).insert(a,c)}}})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f){var d=f.Observability=f.Observability||{};$.extend(d,{track:function(a,c){(d.Configuration&&d.Configuration.track)(a,c)},insert:function(a,c,b){[].splice.apply(a,[c,0].concat(b));return(d.Configuration&&d.Configuration.createInsertDeferredEvent)(a,c,b)},remove:function(a,c,b){var e=a.slice(c,c+b);a.splice(c,b);return(d.Configuration&&d.Configuration.createRemoveDeferredEvent)(a,c,e)},refresh:function(a,c){var b=a.slice(0);[].splice.apply(a,[0,a.length].concat(c));return(d.Configuration&&
d.Configuration.createRefreshDeferredEvent)(a,b,c)},setProperty:function(a,c,b){var e=a[c];a[c]=b;return(d.Configuration&&d.Configuration.createSetPropertyDeferredEvent)(a,c,e,b)},observableInsert:function(a,c,b){(d.Configuration&&d.Configuration.observableInsert)(a,c,b)}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f){f.DataSource=f.defineClass(function(d,a){this._inputData=d;this._take=this._skip=null;this._includeTotalCount=!1;this._observers=[];this._entities=[];this._lastRefreshTotalEntityCount=0;this._flushingDeferredEvents=!1;var c;if(a&&a.entityCollection){if("[object Array]"!==Object.prototype.toString.call(a.entityCollection))throw"Entity collection must be an array";c=a.entityCollection}this._clientEntities=c||[];var b=this;this._clientEntities.deleteEntity=function(a){b._deleteEntity(a)};
f.Observability.track(this._clientEntities,{afterChange:function(a,c,d){b._handleCollectionChange(d)},afterEvent:function(){b._flushDeferredEvents()}})},{dispose:function(){this._observers&&(f.Observability.track(this._clientEntities,null),this._observers=null)},addObserver:function(d){0>$.inArray(d,this._observers)&&this._observers.push(d)},removeObserver:function(d){this._observers=$.grep(this._observers,function(a){return a!==d})},getEntities:function(){return this._clientEntities},getTotalEntityCount:function(){return this._lastRefreshTotalEntityCount+
$.grep(this._entities,function(d){return d.added}).length},getEntityState:function(d){return this._getCachedEntityByEntity(d)?this._inputData.getEntityState(d):null},isPropertyChanged:function(d,a){if(this._getCachedEntityByEntity(d))return this._inputData.isPropertyChanged(d,a);throw"Entity no longer cached in data source.";},getErrors:function(){var d=this;return $.grep(this._inputData.getErrors(),function(a){return!!d._getCachedEntityByEntity(a.entity)})},getDataContext:function(){throw"Unreachable";
},getEntityValidationRules:function(){return this._inputData.getEntityValidationRules()},getEntityId:function(d){return this._inputData.getEntityId(d)},setSort:function(){throw"Unreachable";},setFilter:function(){throw"Unreachable";},setPaging:function(d){d=d||{};this._skip=d.skip;this._take=d.take;this._includeTotalCount=!!d.includeTotalCount},refresh:function(){throw"Unreachable";},revertChange:function(d,a){var c=this._getCachedEntityByEntity(d);if(c)this._inputData.revertChange(d,a),!a&&c.added&&
this._purgeEntity(c.entity);else throw"Entity no longer cached in data source.";},revertChanges:function(d){this._inputData.revertChanges(d);var a=$.grep(this._entities,function(a){return a.added}),c=this;this._executeWithDeferredEvents(function(b){$.each(a,function(a,d){c._purgeEntity(d.entity,b)})})},_onPropertyChanged:function(d,a,c){this._getCachedEntityByEntity(d)&&this._raisePropertyChangedEvent(d,a,c)},_onEntityStateChanged:function(d,a){var c=this;$.each(this._entities,function(a,b){b.added&&
"Unmodified"===c._inputData.getEntityState(b.entity)&&(b.added=!1)});var b=this._getCachedEntityByEntity(d);"Deleted"===a&&b&&(typeof this!==f.LocalDataSource||b.added)&&this._purgeEntity(b.entity);b&&this._raiseEntityStateChangedEvent(d,a)},_raiseRefreshStartEvent:function(){this._raiseEvent("refreshStart")},_raiseRefreshEvent:function(d,a){this._raiseEvent("refresh",d,a)},_raisePropertyChangedEvent:function(d,a,c){this._raiseEvent("propertyChanged",d,a,c)},_raiseEntityStateChangedEvent:function(d,
a){this._raiseEvent("entityStateChanged",d,a)},_raiseEvent:function(d){var a=[].slice.call(arguments,1),c=this._observers.slice(),b=this;$.each(c,function(c,k){$.isFunction(k[d])&&k[d].apply(b,a)})},_getCachedEntityByEntity:function(d){return $.grep(this._entities,function(a){return a.entity===d})[0]},_handleCollectionChange:function(d){switch(d.change){case "insert":d=d.items;if(1<d.length)throw"NYI -- Can only add a single entity to/from an array in one operation.";this._addEntity(d[0]);break;case "remove":if(1<
d.items.length)throw"NYI -- Can only remove a single entity to/from an array in one operation.";throw"NYI -- Cannot apply destructive deletes to a entity collection.  Use 'deleteEntity' for non-destructive delete.";default:throw"NYI -- Array operation '"+d.change+"' is not supported.";}},_addEntity:function(d){this._entities.push({entity:d,added:!0});var a=this._inputData.getEntities();f.Observability.observableInsert(a,a.length,[d])},_deleteEntity:function(d){if(this._getCachedEntityByEntity(d))this._inputData.getEntities().deleteEntity(d);
else throw"Entity no longer cached in data source.";},_purgeEntity:function(d,a){this._entities=$.grep(this._entities,function(a){return a.entity!==d});var c=$.inArray(d,this._clientEntities),c=f.Observability.remove(this._clientEntities,c,1);a?a.deferEvent(c):c&&c()},_processFilter:function(d){var a=d.property,c=d.value,b;if(d.operator){var e={"<":["<","islessthan","lessthan","less","lt"],"<=":["<=","islessthanorequalto","lessthanequal","lte"],"==":"==,isequalto,equals,equalto,equal,eq".split(","),
"!=":"!=,isnotequalto,notequals,notequalto,notequal,neq,not".split(","),">=":[">=","isgreaterthanorequalto","greaterthanequal","gte"],">":[">","isgreaterthan","greaterthan","greater","gt"]},k=d.operator.toLowerCase(),g;for(g in e)if(-1<$.inArray(k,e[g])){b=g;break}b||(b=d.operator)}else b="==";return{filterProperty:a,filterOperator:b,filterValue:c}},_flushDeferredEvents:function(){},_completeRefresh:function(d,a,c){this._lastRefreshTotalEntityCount=a;var b,a=this.getEntities();a.length!==d.length?
b=!0:$.each(a,function(a,c){if(c!==d[a])return b=!0,!1});if(b){var e=this;this._entities=$.map(d,function(a){var b=0<$.grep(e._entities,function(b){return b.entity===a&&b.added}).length;return{entity:a,added:b}});(a=f.Observability.refresh(this._clientEntities,d))&&a()}var a=this.getEntities(),k=this.getTotalEntityCount();c&&c.completed&&$.isFunction(c.completed)&&c.completed(a,k);this._raiseRefreshEvent(a,k)},_executeWithDeferredEvents:function(d){this._assertNotFlushingDeferredEvents();var a=[],
d=d({deferEvent:function(c){c&&a.push(c)}});try{this._flushingDeferredEvents=!0,$.each(a,function(a,b){b()})}finally{this._flushingDeferredEvents=!1}return d},_assertNotFlushingDeferredEvents:function(){if(this._flushingDeferredEvents)throw"Issuing side-effecting operations during event callbacks is not supported.";}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f,d){f.EntitySet=f.defineClass(function(a,c){this._dataContext=a;this._entityType=c;this._observers=[];this._updatedEntities=[];this._originalEntities=[];this._entityStates={};this._addedEntities=[];this._errors=[];this._clientEntities=[];this._deferredEvents=[];this._childEntitiesCollections={};var b=this;f.Observability.track(this._clientEntities,{afterChange:function(a,c,d){b._handleCollectionChange(d)},afterEvent:function(){b._flushDeferredEventsFromAddOrUpdate()}});this._clientEntities.deleteEntity=
function(a){b._deleteEntity(a)}},{dispose:function(){this._observers&&(f.Observability.track(this._clientEntities,null),this._observers=null)},addObserver:function(a){0>$.inArray(a,this._observers)&&this._observers.push(a)},removeObserver:function(a){this._observers=$.grep(this._observers,function(c){return c!==a})},getEntities:function(){return this._clientEntities},getEntityState:function(a){return(a=this.getEntityId(a))?this._entityStates[a]:null},getEntityId:function(a){var c=this._getAddedEntityFromEntity(a);
if(c)return c.clientId;a=$.inArray(a,this._updatedEntities);return 0<=a?this._getServerEntityId(this._originalEntities[a]).toString():null},isPropertyChanged:function(a,c){var b=this.getEntityId(a);switch(this._entityStates[b]){case "ClientUpdated":case "ServerUpdating":return b=this._getEntityIndexFromId(b),this._originalEntities[b][c]!==this._updatedEntities[b][c];case d:case "Deleted":throw"Entity no longer cached in data source.";default:return!1}},getErrors:function(){return this._errors},revertChange:function(a,
c){var b=this.getEntityId(a),e=this._entityStates[b];if(!e||"Deleted"===e)throw"Entity no longer cached in data source.";var d=this;this._executeWithDeferredEvents(function(g){if(c){if("ClientUpdated"!==e)throw"Property change cannot be reverted for entity in state '"+e+"'.";var i=d._getEntityIndexFromId(b),i=d._originalEntities[i][c],h=f.Observability.setProperty(a,c,i);g.deferEvent(h);d._handlePropertyChangeInternal(a,c,i,g)}else if("ClientDeleted"===e||"ClientUpdated"===e)d._revertToOriginalEntity(b,
g),d._errors=$.grep(d._errors,function(b,c){return c.entity!==a}),d._updateEntityState(b,"Unmodified",g);else if("ClientAdded"===e)d._purgeUncommittedAddedEntity(d._getAddedEntityFromId(b),!0,g);else throw"Entity changes cannot be reverted for entity in state '"+e+"'.";})},revertChanges:function(){var a=this;this._executeWithDeferredEvents(function(c){a.__revertChanges(c)})},__hasUncommittedEdits:function(){var a=!1;$.each(this._entityStates,function(c,b){"Unmodified"!==b&&(a=!0)});return a},__loadEntities:function(a,
c){var b=this,e=[],d=[],g=this._updatedEntities.length;$.each(a,function(a,h){var g,f=b._getServerEntityId(h),j=b._getEntityIndexFromServerId(f);0<=j?(f=b._originalEntities[j],g=b._updatedEntities[j],b._mergeOntoUpdatedEntity(g,h,f,c),b._originalEntities[j]=h):(g=$.extend({},h),b._addAssociationProperties(g),j=f.toString(),b._trackObservableForEntity(g),b._entityStates[j]="Unmodified",b._updatedEntities.push(g),b._originalEntities.push(h),d.push(g));e.push(g)});0<d.length&&(g=f.Observability.insert(this._clientEntities,
g,d),c.deferEvent(g));return e},__getEditedEntities:function(){var a=this,c=[];$.each(this._entityStates,function(b,e){0===e.indexOf("Client")&&c.push(a._getEntityFromId(b))});return c},__getEntityEdit:function(a){var c=this.getEntityId(a),b=this,e,d,g=this._getEntityIndexFromId(c),a=function(a){return $.extend({__type:b._entityType},a)};switch(this._entityStates[c]){case "ClientUpdated":e="ServerUpdating";d={Operation:3,Entity:a(this._updatedEntities[g]),OriginalEntity:a(this._originalEntities[g])};
break;case "ClientAdded":e="ServerAdding";g=this._getAddedEntityFromId(c);d={Operation:2,Entity:a(g.entity)};break;case "ClientDeleted":e="ServerDeleting";d={Operation:4,Entity:a(this._originalEntities[g])};break;default:throw"Unrecognized entity state.";}return{updateEntityState:function(a){b._updateEntityState(c,e,a)},operation:d,succeeded:function(a,e){return b._handleSubmitSucceeded(c,d,a,e)},failed:function(a,e){b._handleSubmitFailed(c,d,a,e)}}},__revertChanges:function(a){var c;$.each(this._entityStates,
function(a,b){if(0===b.indexOf("Server"))return c=!0,!1});if(c)throw"Can't revert changes while a commit is in progress.";var b=this,e=$.grep(this._addedEntities,function(a){return a.entity&&0>$.inArray(a.entity,b._updatedEntities)});0<e.length&&(this._addedEntities=$.grep(this._addedEntities,function(a){return 0>$.inArray(a,e)}),$.each(e,function(c,e){b._purgeUncommittedAddedEntity(e,!0,a)}));this._errors=[];for(var d in this._entityStates)0===this._entityStates[d].indexOf("Client")&&(this._revertToOriginalEntity(d,
a),this._updateEntityState(d,"Unmodified",a))},__handleEntitySetChanged:function(a,c){var b=(this._dataContext.__getMetadata(this._entityType)||{}).fields;if(b)for(var e in this._childEntitiesCollections){var d=this._childEntitiesCollections[e],g=this._getEntityFromId(e),i;for(i in d){var h=b[i];if(h.type===a){var l=d[i],m=this._computeAssociatedEntities(g,h),h=$.grep(m,function(a){return 0>$.inArray(a,l)});$.each(h,function(a,b){var e=f.Observability.insert(l,l.length,[b]);c.deferEvent(e)});var j=
$.grep(l,function(a){return 0>$.inArray(a,m)});$.each(j,function(a,b){var e=$.inArray(b,l),e=f.Observability.remove(l,e,1);c.deferEvent(e)});(0<h.length||0<j.length)&&$.dataSource.unwrapHack(l).__syncToNewEntities()}}}},__getEntityType:function(){return this._entityType},_handleCollectionChange:function(a){switch(a.change){case "insert":a=a.items;if(1<a.length)throw"NYI -- Can only add a single entity to/from an array in one operation.";var c=a[0],b=this;this._executeWithDeferredEvents(function(a){b._addEntity(c,
a)},!0);break;case "remove":if(1<a.items.length)throw"NYI -- Can only remove a single entity to/from an array in one operation.";throw"NYI -- Cannot apply destructive deletes to a entity collection.  Use 'deleteEntity' for non-destructive delete.";default:throw"NYI -- Array operation '"+a.change+"' is not supported.";}},_addEntity:function(a,c,b){if(0<=$.inArray(a,this._updatedEntities)||this._getAddedEntityFromEntity(a))throw"Entity already in data source.";var e="added"+Math.floor(Math.random()*
Math.pow(2,32)+1).toString();this._addedEntities.push({entity:a,clientId:e});this._trackObservableForEntity(a);this._entityStates[e]="Unmodified";this._addAssociationProperties(a);this._updateEntityState(e,"ClientAdded",c);b||this._dataContext.__commitEntityIfImplicit(this,a,c);c.entitySetChanged(this._entityType)},_deleteEntity:function(a){var c=this;this._executeWithDeferredEvents(function(b){var e=c.getEntityId(a),d=c._getEntityIndexFromId(e),g=c._getAddedEntityFromId(e);if(0>d&&g)if("ClientAdded"===
c._entityStates[e])c._purgeUncommittedAddedEntity(g,!0,b);else throw"NYI -- Can't edit a entity while previous edits are being committed.";else{if(0>d)throw"Entity no longer cached in data source.";if(0===c._entityStates[e].indexOf("Server"))throw"NYI -- Can't edit a entity while previous edits are being committed.";c._updateEntityState(e,"ClientDeleted",b);c._dataContext.__commitEntityIfImplicit(c,a,b)}})},_updateEntity:function(a,c){var b=$.inArray(a,this._updatedEntities);if(0>b&&this._getAddedEntityFromEntity(a)){if("ClientAdded"!==
this._entityStates[this.getEntityId(a)])throw"NYI -- Can't update an added entity while it's being committed.";}else{if(0>b)throw"Entity no longer cached in data source.";b=this.getEntityId(a);if(0===this._entityStates[b].indexOf("Server"))throw"NYI -- Can't edit a entity while previous edits are being committed.";this._updateEntityState(b,"ClientUpdated",c)}this._dataContext.__commitEntityIfImplicit(this,a,c)},_updateEntityState:function(a,c,b,e,d){var g=this._entityStates[a];this._entityStates[a]&&
(this._entityStates[a]=c);d=d||this._getEntityFromId(a);e&&(a=JSON.parse(e),this._errors.push({entity:d,error:a}));if(g!==c){var i=this;b.deferEvent(function(){i._raiseEntityStateChangedEvent(d,c)})}},_purgeEntityAtIndex:function(a,c,b){var e=this._updatedEntities[a],d=this.getEntityId(e);f.Observability.track(e,null);this._updatedEntities=$.grep(this._updatedEntities,function(b,c){return c!==a});this._originalEntities=$.grep(this._originalEntities,function(b,c){return c!==a});this._purgeFromClientEntities(e,
c,b);delete this._entityStates[d];this._disposeChildEntitiesCollections(d);this._getAddedEntityFromId(d)&&(this._addedEntities=$.grep(this._addedEntities,function(a){return a.clientId!==d}));this._errors=$.grep(this._errors,function(a,b){return b.entity!==e})},_raisePropertyChangedEvent:function(a,c,b){this._raiseEvent("propertyChanged",a,c,b)},_raiseEntityStateChangedEvent:function(a,c){this._raiseEvent("entityStateChanged",a,c)},_raiseEvent:function(a){var c=[].slice.call(arguments,1),b=this._observers.slice();
$.each(b,function(b,d){$.isFunction(d[a])&&d[a].apply(null,c)})},_getServerEntityId:function(a){return this._dataContext.__getMetadata(this._entityType).getServerId(a)},_getEntityIndexFromId:function(a){var c=this._getAddedEntityFromId(a);if(c){if(c.serverId===d)return-1;a=c.serverId.toString()}for(var c=-1,b=0;b<this._originalEntities.length;b++)if(this._getServerEntityId(this._originalEntities[b]).toString()===a){c=b;break}return c},_getEntityIndexFromServerId:function(a){for(var c=-1,b=0;b<this._originalEntities.length;b++)if(this._getServerEntityId(this._originalEntities[b])===
a){c=b;break}return c},_trackObservableForEntity:function(a){var c=this;f.Observability.track(a,{afterChange:function(a,e,d){c._handlePropertyChange(a,d)},afterEvent:function(){c._flushDeferredEventsFromAddOrUpdate()}})},_handlePropertyChange:function(a,c){var b=c.path,e=c.value;if(""!==b){var d=this.getEntityId(a);if(!("Unmodified"===this._entityStates[d]&&a[b]===this._originalEntities[this._getEntityIndexFromId(d)][b])){var g=this;this._executeWithDeferredEvents(function(c){g._handlePropertyChangeInternal(a,
b,e,c)},!0)}}},_handlePropertyChangeInternal:function(a,c,b,e){var d=this;e.deferEvent(function(){d._raisePropertyChangedEvent(a,c,b)});this._updateEntity(a,e);e.entitySetChanged(this._entityType)},_mergeOntoUpdatedEntity:function(a,c,b,e){var d=this,g;$.each(c,function(c,h){if(!(b&&a[c]!==b[c])&&a[c]!==h){g=!0;var l=f.Observability.setProperty(a,c,h);e.deferEvent(l);e.deferEvent(function(){d._raisePropertyChangedEvent(a,c,h)})}});g&&e.entitySetChanged(this._entityType)},_getAddedEntityFromId:function(a){return $.grep(this._addedEntities,
function(c){return c.clientId===a})[0]},_getAddedEntityFromEntity:function(a){return $.grep(this._addedEntities,function(c){return c.entity===a})[0]},_handleSubmitSucceeded:function(a,c,b,e){var d=!0,g=this._getEntityFromId(a);switch(c.Operation){case 2:if(b.ValidationErrors){var d=!1,i=this;$.each(b.ValidationErrors,function(a,b){i._errors.push({entity:g,error:b})});this._updateEntityState(a,"ClientAdded",e)}else{var c=b.Entity,b=this._getAddedEntityFromId(a),h=b.entity;b.serverId=this._getServerEntityId(c);
this._updatedEntities.push(h);this._originalEntities.push(c);this._revertToOriginalEntity(b.clientId,e);this._updateEntityState(a,"Unmodified",e)}break;case 3:c=b.Entity;this._originalEntities[this._getEntityIndexFromId(a)]=c;this._revertToOriginalEntity(a,e);this._updateEntityState(a,"Unmodified",e);break;case 4:this._purgeEntityAtIndex(this._getEntityIndexFromId(a),!0,e),this._updateEntityState(a,"Deleted",e,null,g)}d&&(this._errors=$.grep(this._errors,function(a,b){return b.entity!==g}));return d},
_handleSubmitFailed:function(a,c,b,e){var d;switch(c.Operation){case 2:d="ClientAdded";break;case 3:d="ClientUpdated";break;case 4:d="ClientDeleted"}this._updateEntityState(a,d,e,b.responseText)},_revertToOriginalEntity:function(a,c){var b=this._getEntityIndexFromId(a);this._mergeOntoUpdatedEntity(this._updatedEntities[b],this._originalEntities[b],null,c)},_purgeUncommittedAddedEntity:function(a,c,b){var e=a.clientId,d=a.entity;f.Observability.track(d,null);this._addedEntities=$.grep(this._addedEntities,
function(b){return b!==a});delete this._entityStates[e];this._disposeChildEntitiesCollections(e);this._errors=$.grep(this._errors,function(a,b){return b.entity!==d});this._purgeFromClientEntities(d,c,b);this._updateEntityState(e,"Deleted",b,null,d)},_purgeFromClientEntities:function(a,c,b){a=$.inArray(a,this._clientEntities);a=f.Observability.remove(this._clientEntities,a,1);c&&b.deferEvent(a);b.entitySetChanged(this._entityType)},_getEntityFromId:function(a){var c=this;return $.grep(this.getEntities(),
function(b){return c.getEntityId(b)===a})[0]},_executeWithDeferredEvents:function(a,c){this._assertNotFlushingDeferredEvents();var b=[],d,k={deferEvent:function(a){a&&b.push(a)},entitySetChanged:function(){d=!0}},g=a(k);d&&this._dataContext.__entitySetChanged(this._entityType,k);if(c){var i=this;$.each(b,function(a,b){i._deferredEvents.push(b)})}else this._flushDeferredEvents(b);return g},_flushDeferredEventsFromAddOrUpdate:function(){if(0!==this._deferredEvents.length){var a=this._deferredEvents;
this._deferredEvents=[];this._flushDeferredEvents(a)}},_flushDeferredEvents:function(a){try{this._flushingDeferredEvents=!0,$.each(a,function(a,b){b()})}finally{this._flushingDeferredEvents=!1}},_assertNotFlushingDeferredEvents:function(){if(this._flushingDeferredEvents)throw"Issuing side-effecting operations during event callbacks is not supported.";},_addAssociationProperties:function(a){var c=(this._dataContext.__getMetadata(this._entityType)||{}).fields;if(c){var b=this;$.each(c,function(c,d){d.association&&
(d.association.isForeignKey?(a["get_"+c]=function(){return b._getParentEntity(a,c)},a["set_"+c]=function(d){return b._setParentEntity(a,c,d)}):d.array&&(a["get_"+c]=function(){return b._getChildEntities(a,c)}))})}},_getParentEntity:function(a,c){var b=this._dataContext.__getMetadata(this._entityType).fields[c];return this._computeAssociatedEntities(a,b)[0]||null},_setParentEntity:function(a,c,b){var c=this._dataContext.__getMetadata(this._entityType).fields[c],e=this._dataContext.getEntitySet(c.type);
if(0>$.inArray(b,e.getEntities()))throw"Parent entity is not in the parent entity set for this association.";if(0<(e.getEntityState(b)||"").indexOf("Add"))throw"NYI -- Cannot set foreign keys to key values computed from added entities.  Commit your parent entity first.";var e=c.association.otherKey,k=b?b[e[0]]:null;if(k===d)throw"Parent entity has no value for its '"+e[0]+"' key property.";var g=c.association.thisKey,c=a[g[0]],i;if(b){if(c===d||c!==k)i=!0}else null!==c&&(i=!0);if(i){var h=this;this._executeWithDeferredEvents(function(b){var c=
f.Observability.setProperty(a,g[0],k);b.deferEvent(c);h._handlePropertyChangeInternal(a,g[0],k,b)})}},_getChildEntities:function(a,c){var b=this.getEntityId(a),e=this._childEntitiesCollections[b];e||(e=this._childEntitiesCollections[b]={});var k=e[c];if(!k){var g=this._dataContext.__getMetadata(this._entityType).fields[c],k=this._computeAssociatedEntities(a,g),i=this,b=new f.AssociatedEntitiesDataSource(this._dataContext,g.type,k,function(b){if(0<(i.getEntityState(a)||"").indexOf("Add"))throw"NYI -- Cannot set foreign keys to key values computed from added entities.  Commit the parent entity first.";
var c=g.association.thisKey,e=a[c[0]];if(e===d)throw"Parent entity has no value for its '"+c[0]+"' key property.";c=g.association.otherKey;i._dataContext.getEntitySet(g.type)._handleAddToChildEntitiesCollection(b,c,e,function(){$.dataSource.unwrapHack(k).__syncToNewEntities()})},function(){i._dataContext.getEntitySet(g.type)._flushDeferredEventsFromAddOrUpdate()});$.dataSource.wrapHack(k,b);e[c]=k}return k},_computeAssociatedEntities:function(a,c){var b=a[c.association.thisKey[0]];return this._dataContext.getEntitySet(c.type)._getTargetEntities(c.association.otherKey,
b)},_getTargetEntities:function(a,c){return $.grep(this._clientEntities,function(b){b=b[a[0]];return b!==d&&b===c})},_disposeChildEntitiesCollections:function(a){var c=this._childEntitiesCollections[a];c&&$.each(c,function(a,c){$([c]).dataSource().destroy()});delete this._childEntitiesCollections[a]},_handleAddToChildEntitiesCollection:function(a,c,b,e){var k=this;this._executeWithDeferredEvents(function(g){var i=a[c[0]],i=i===d||i!==b,h;0>$.inArray(a,k.getEntities())&&(g.deferEvent(f.Observability.insert(k._clientEntities,
k._clientEntities.length,[a])),k._addEntity(a,g,i),h=!0);i&&(g.deferEvent(f.Observability.setProperty(a,c[0],b)),k._handlePropertyChangeInternal(a,c[0],b,g),h=!0);h&&e()},!0)}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f){f.DataContext=f.defineClass(function(d,a,c){this._serviceUrl=d;this._changeTracking=!!c;if(a){c=f[a+"DataProvider"];if(!c)throw"There is no provider available for the format '"+a+"'";d=new c(d)}else d=new f.DataProvider(d);this._dataProvider=d;this._observers=[];this._entitySets={};this._flushingDeferredEvents=!1;this._metadata={}},{dispose:function(){},addObserver:function(d){0>$.inArray(d,this._observers)&&this._observers.push(d)},removeObserver:function(d){this._observers=$.grep(this._observers,
function(a){return a!==d})},getEntitySet:function(d){var a=this._entitySets[d];a||(a=this._entitySets[d]=new f.EntitySet(this,d));return a},getErrors:function(){var d=[];$.each(this._entitySets,function(a,c){var b=[d.length,0].concat(c.getErrors());[].splice.apply(d,b)});return d},commitChanges:function(){if(!this._changeTracking)throw"Data context must be in change-tracking mode to explicitly commit changes.";var d=[];$.each(this._entitySets,function(a,b){var e=$.map(b.__getEditedEntities(),function(a){return{entitySet:b,
entity:a}}),e=[d.length,0].concat(e);[].splice.apply(d,e)});var a=this;this._executeWithDeferredEvents(function(c){a._submitChanges(d,c)})},revertChanges:function(){var d=this;this._executeWithDeferredEvents(function(a){$.each(d._entitySets,function(c,b){b.__revertChanges(a)})})},merge:function(d,a,c){var b=this,e;this._executeWithDeferredEvents(function(k){c&&$.each(c,function(a,c){b.getEntitySet(a).__loadEntities(c,k)});var g=a&&b.getEntitySet(a);e=g?g.__loadEntities(d,k):[]});return e},addMetadata:function(d,
a){if(!this._metadata[d]){var c=this._entitySets[d];if(c&&c.getEntities().length)throw"Cannot add metadata for type once data of that type has been merged into this DataContext.";this._metadata[d]=a}},__load:function(d,a){$.each(this._entitySets,function(a,b){if(b.__hasUncommittedEdits())throw"Load is not allowed while the data source contains uncommitted edits.";});var c=this._dataProvider,b=this;c.get(d.queryName,d.queryParameters,d).done(function(d){d=c.load(d,b);a(b.getEntitySet(d.type),d.entities,
d.totalCount)})},__commitEntityIfImplicit:function(d,a,c){this._changeTracking||this._submitChanges([{entitySet:d,entity:a}],c)},__entitySetChanged:function(d,a){this._distributeEntitySetChanged(d,a)},__getMetadata:function(d){return this._metadata[d]},_raiseCommitEvent:function(){this._raiseEvent("commit")},_raiseCommittingEvent:function(){this._raiseEvent("commitStart")},_raiseEvent:function(d){var a=[].slice.call(arguments,1),c=this._observers.slice();$.each(c,function(b,c){$.isFunction(c[d])&&
c[d].apply(null,a)})},_submitChanges:function(d,a){this._raiseCommittingEvent();var c=$.map(d,function(a){return a.entitySet.__getEntityEdit(a.entity)});$.each(c,function(b,c){c.updateEntityState(a)});var b=this;this._dataProvider.post("SubmitChanges",{changeSet:$.map(c,function(a,b){return $.extend({Id:b.toString()},a.operation)})}).then(function(a){b._executeWithDeferredEvents(function(b){for(var d=0;d<a.length;d++)if(!c[d].succeeded(a[d],b))return!0;return!1})||b._raiseCommitEvent()},function(a){b._executeWithDeferredEvents(function(b){$.each(c,
function(c,d){d.failed(a,b)})})})},_executeWithDeferredEvents:function(d){this._assertNotFlushingDeferredEvents();var a=[],c={},b={deferEvent:function(b){b&&a.push(b)},entitySetChanged:function(a){c[a]=!0}},d=d(b),e;for(e in c)this._distributeEntitySetChanged(e,b);try{this._flushingDeferredEvents=!0,$.each(a,function(a,b){b()})}finally{this._flushingDeferredEvents=!1}return d},_distributeEntitySetChanged:function(d,a){for(var c in this._entitySets)this._entitySets[c].__handleEntitySetChanged(d,a)},
_assertNotFlushingDeferredEvents:function(){if(this._flushingDeferredEvents)throw"Issuing side-effecting operations during event callbacks is not supported.";}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f,d){function a(a){var c={};if(a.$where||a.where)c.$where=a.$where||a.where;else if(a.filters){var k="";$.each(a.filters,function(a,b){0<a&&(k+=" AND ");var c;if(b.filterValue===d)c=k+b.filterProperty;else{c=k;var e;a:{e=b.filterProperty;var g=b.filterValue,f=b.filterOperator||"==";"string"===typeof g&&(g='"'+g+'"');switch(f){case "<":case "<=":case "==":case "!=":case ">=":case ">":e=e+f+g;break a;case "StartsWith":case "EndsWith":case "Contains":e=e+"."+f+"("+g+")";break a;default:throw"The operator '"+
f+"' is not supported.";}}c+=e}k=c});c.$where=k}if(a.$orderby||a.orderby)c.$orderby=a.$orderby||a.orderby;else if(a.sort){var g="";"[object String]"===Object.prototype.toString.call(a.sort)?g=a.sort:"[object Array]"===Object.prototype.toString.call(a.sort)?$.each(a.sort,function(a,b){0<a&&(g+=",");g+=b.property+(b.direction?" "+b.direction:"")}):g=a.sort.property+(a.sort.direction?" "+a.sort.direction:"");c.$orderby=g}if(a.$skip||a.skip)c.$skip=a.$skip||a.skip;if(a.$take||a.take)c.$take=a.$take||
a.take;if(a.$includeTotalCount||a.includeTotalCount)c.$includeTotalCount=a.$includeTotalCount||a.includeTotalCount;return c}function c(a){a&&$.each(a||{},function(c,d){$.isArray(d)&&(a[c]=JSON.stringify(d))});return a}f.DataProvider=f.defineClass(function(a){this._serviceUrl=a},{get:function(b,d,k){var g="/"!==this._serviceUrl.substring(this._serviceUrl.length-1)?"/":"";return $.ajax({url:this._serviceUrl+g+"json/"+b,data:$.extend({},c(d),a(k||{})),dataType:"json"})},load:function(a,c){var d;$.each(a,
function(a){if(/Result$/.test(a))return d=a,!1});var g=a[d];$.each(g.Metadata,function(a,b){c.addMetadata(b.type,{getServerId:function(a){return a[b.key[0]]},fields:b.fields,rules:b.rules,messages:b.messages})});$.each(g.RootResults,function(a,b){delete b.__type});var f={};g.IncludedResults&&$.each(g.IncludedResults,function(a,b){var c=b.__type;delete b.__type;(f[c]||(f[c]=[])).push(b)});var h=g.Metadata[0].type;return{entities:c.merge(g.RootResults,h,f),type:h,totalCount:g.TotalCount||0}},post:function(a,
c){var d=$.Deferred(),g="/"!==this._serviceUrl.substring(this._serviceUrl.length-1)?"/":"",f=JSON.stringify(c);$.ajax({url:this._serviceUrl+g+"json/"+a,contentType:"application/json",data:f,dataType:"json",type:"POST",success:function(c){c=c[a+"Result"];$.each(c,function(a,b){b.Entity&&delete b.Entity.__type});d.resolve(c)},error:function(a){d.reject(a)}});return d.promise()}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f){f.RemoteDataSource=f.deriveClass(f.DataSource,function(d,a,c,b){this._filters=this._sort=this._entitySet=null;var e,k,g,i;if(b&&(e=b.format,k=b.queryParameters,g=b.bufferChanges,i=b.dataContext,!i&&b.entityCollection&&0!==b.entityCollection.length))throw"NYI -- Currently, entity collection must be empty to bind to a data source.";this._queryName=a;this._queryParameters=k;i||(i=new f.DataContext(d,e,!!g));this._dataContext=i;var h=this;this._dataContextObserver={commitStart:function(){h._onCommitStart()},
commit:function(){h._onCommit()}};this._dataContext.addObserver(this._dataContextObserver);this._entitySetObserver={propertyChanged:function(a,b,c){h._onPropertyChanged(a,b,c)},entityStateChanged:function(a,b){h._onEntityStateChanged(a,b)}};this._super.constructor.call(this,{getEntities:function(){return h._entitySet.getEntities()},getEntityState:function(a){return h._entitySet.getEntityState(a)},getEntityValidationRules:function(){return{rules:h._dataContext.__getMetadata(h._getEntityType()).rules,
messages:h._dataContext.__getMetadata(h._getEntityType()).messages}},isPropertyChanged:function(a,b){return h._entitySet.isPropertyChanged(a,b)},getErrors:function(){return h._dataContext.getErrors()},revertChange:function(a,b){return h._entitySet.revertChange(a,b)},revertChanges:function(a){a?h._dataContext.revertChanges():h._entitySet.revertChanges()},getEntityId:function(a){return h._entitySet.getEntityId(a)}},b)},{dispose:function(){f.DataSource.prototype.dispose.apply(this);this._dataContextObserver&&
(this._dataContext.removeObserver(this._dataContextObserver),this._dataContextObserver=null);this._entitySetObserver&&this._entitySet&&(this._entitySet.removeObserver(this._entitySetObserver),this._entitySetObserver=null)},getDataContext:function(){return this._dataContext},setSort:function(d){this._sort=d},setFilter:function(d){if(d)if("[object Array]"===Object.prototype.toString.call(d)){var a=this;this._filters=$.map(d,function(c){return a._processFilter(c)})}else this._filters=[this._processFilter(d)];
else this._filters=null},refresh:function(d){this._raiseRefreshStartEvent();var a=this;this._dataContext.__load({queryName:this._queryName,queryParameters:this._queryParameters,filters:this._filters,sort:this._sort,skip:this._skip,take:this._take,includeTotalCount:this._includeTotalCount},function(c,b,e){a._bindToEntitySet(c);a._completeRefresh(b,e,d)})},commitChanges:function(){this._dataContext.commitChanges()},_onCommitStart:function(){this._raiseCommitStartEvent()},_onCommit:function(){this._raiseCommitEvent()},
_raiseCommitStartEvent:function(){this._raiseEvent("commitStart")},_raiseCommitEvent:function(){this._raiseEvent("commit")},_bindToEntitySet:function(d){d!==this._entitySet&&(this._entitySet&&this._entitySet.removeObserver(this._entitySetObserver),(this._entitySet=d)&&this._entitySet.addObserver(this._entitySetObserver))},_getEntityType:function(){return this._entitySet.__getEntityType()}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f){f.AssociatedEntitiesDataSource=f.deriveClass(f.RemoteDataSource,function(d,a,c,b,e){this._super.constructor.call(this,null,null,a,{dataContext:d,entityCollection:c});this._bindToEntitySet(d.getEntitySet(a));this._handleAddEntity=b;this._flushDeferredEventsFromAdd=e;this.__syncToNewEntities()},{getTotalEntityCount:function(){return this._entities.length},setSort:function(){throw"Associated entities collections don't support query.";},setFilter:function(){throw"Associated entities collections don't support query.";
},setPaging:function(){throw"Associated entities collections don't support query.";},refresh:function(){throw"Associated entities collections refresh implicitly.";},__syncToNewEntities:function(){this._entities=$.map(this._clientEntities,function(d){return{entity:d}})},_addEntity:function(d){this._handleAddEntity(d)},_purgeEntity:function(){},_flushDeferredEvents:function(){this._flushDeferredEventsFromAdd()}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j,f,d){f.LocalDataSource=f.deriveClass(f.DataSource,function(a,c){if(c&&c.entityCollection&&0!==c.entityCollection.length)throw"NYI -- Currently, entity collection must be empty to bind to a data source.";if(!("_lastRefreshTotalEntityCount"in a||a instanceof f.EntitySet))throw"Currently, local data sources only accept DataSource- and EntitySet-typed input data.";this._inputDataSourceOrEntitySet=a;this._filter=this._sort=null;this._refreshAllInProgress=!1;this._resultsStale=!0;this._deferredResultsStaleEvent=
!1;var b=this;this._observer={refreshStart:function(){b._onRefreshStart()},refresh:function(a){b._onRefresh(a)},propertyChanged:function(a,c,d){b._onPropertyChanged(a,c,d)},entityStateChanged:function(a,c){b._onEntityStateChanged(a,c)},commit:function(){b._onCommit()},resultsStale:function(){b._onResultsStale()}};a.addObserver(this._observer);this._innerArrayChangeHandler=function(a,c){b._handleInnerCollectionChange(a,c)};$([a.getEntities()]).bind("arrayChange",this._innerArrayChangeHandler);this._super.constructor.call(this,
{getEntities:function(){return a.getEntities()},getEntityState:function(b){return a.getEntityState(b)},getEntityValidationRules:function(){return a.getEntityValidationRules()},isPropertyChanged:function(b,c){return a.isPropertyChanged(b,c)},getErrors:function(){return a.getErrors()},revertChange:function(b,c){return a.revertChange(b,c)},revertChanges:function(b){return a.revertChanges(b)},getEntityId:function(b){return a.getEntityId(b)}},c)},{dispose:function(){f.DataSource.prototype.dispose.apply(this);
this._observer&&(this._inputDataSourceOrEntitySet.removeObserver(this._observer),this._observer=null);this._innerArrayChangeHandler&&($([this._inputDataSourceOrEntitySet.getEntities()]).unbind("arrayChange",this._innerArrayChangeHandler),this._innerArrayChangeHandler=null)},getDataContext:function(){return this._inputDataSourceOrEntitySet.getDataContext&&this._inputDataSourceOrEntitySet.getDataContext()},setSort:function(a){this._sort=a},setFilter:function(a){this._filter=a&&this._createFilterFunction(a)},
refresh:function(a){function c(c){b._resultsStale=!1;c=b._applyQuery(c);b._completeRefresh(c.entities,c.totalCount,a)}this._raiseRefreshStartEvent();var b=this;a&&a.all&&this._inputDataSourceOrEntitySet.refresh?(this._refreshAllInProgress=!0,this._inputDataSourceOrEntitySet.refresh({all:!0,completed:function(a){c(a);b._refreshAllInProgress=!1}})):setTimeout(function(){c(b._inputDataSourceOrEntitySet.getEntities())})},areResultsStale:function(){return this._resultsStale},_onRefreshStart:function(){},
_onRefresh:function(a){if(!this._refreshAllInProgress&&!this._resultsStale){var c=!1,b=this._applyQuery(a);if(this.totalCount!==b.totalCount)c=!0;else if(a=this.getEntities(),b=b.entities,a.length!==b.length)c=!0;else for(var d=0;d<a.length;d++)if(a[d]!==b[d]){c=!0;break}c&&this._setResultsStale()}},_normalizePropertyValue:function(a,c){return a[c]||""},_onPropertyChanged:function(a,c,b){f.DataSource.prototype._onPropertyChanged.apply(this,arguments);if(!this._refreshAllInProgress&&!this._resultsStale){var d=
!1;this._filter&&!this._filter(a)&&(d=!0);this._getCachedEntityByEntity(a)&&this._sort&&(d=$.isFunction(this._sort)?!0:"[object Array]"===Object.prototype.toString.call(this._sort)?0<$.grep(this._sort,function(a){return a.property===c}).length:this._sort.property===c);d&&this._setResultsStale()}},_onCommit:function(){},_onResultsStale:function(){},_raiseResultsStaleEvent:function(){this._deferredResultsStaleEvent=!1;this._raiseEvent("resultsStale")},_createFilterFunction:function(a){function c(a){if($.isFunction(a))return a;
var a=b._processFilter(a),c=a.filterProperty,d=a.filterValue,e;switch(a.filterOperator){case "<":e=function(a){return a<d};break;case "<=":e=function(a){return a<=d};break;case "==":e=function(a){return a==d};break;case "!=":e=function(a){return a!=d};break;case ">=":e=function(a){return a>=d};break;case ">":e=function(a){return a>d};break;case "Contains":e=function(a){"string"===typeof a&&"string"===typeof d&&(a=a.toLowerCase(),d=d.toLowerCase());return 0<=a.indexOf(d)};break;default:throw"Unrecognized filter operator.";
}return function(a){a=b._normalizePropertyValue(a,c);return e(a)}}var b=this;if("[object Array]"===Object.prototype.toString.call(a)){var d=$.map(a,function(a){return c(a)});return function(a){for(var b=0;b<d.length;b++)if(!d[b](a))return!1;return!0}}return c(a)},_getSortFunction:function(){function a(a){return function(b,d){var f=0===(a.direction||"asc").toLowerCase().indexOf("asc"),h=c._normalizePropertyValue(b,a.property),j=c._normalizePropertyValue(d,a.property);return h==j?0:h>j?f?1:-1:f?-1:
1}}var c=this;if(this._sort){if($.isFunction(this._sort))return this._sort;if("[object Array]"===Object.prototype.toString.call(this._sort)){var b;$.each(this._sort,function(c,d){var g=a(d);b=b?function(a,b){return function(c,d){var e=a(c,d);return 0===e?b(c,d):e}}(b,g):g});return b}return a(this._sort)}return null},_applyQuery:function(a){var c=this,a=this._filter?$.grep(a,function(a){return c._filter(a)}):a,b=this._getSortFunction(),a=b?a.sort(b):a,b=a.slice(this._skip||0);this._take&&(b=b.slice(0,
this._take));return{entities:b,totalCount:this._includeTotalCount?a.length:d}},_handleInnerCollectionChange:function(a,c){if(!this._refreshAllInProgress&&!this._resultsStale){var b=this,d=!1,f=function(a){return 0<$.grep(a,function(a){return!!b._getCachedEntityByEntity(a)}).length};switch(c.change){case "insert":f=c.items;if(0<f.length){var g=this._filter||function(){return!0};0<$.grep(f,function(a){return g(a)&&0===$.grep(b._entities,function(b){return b.entity===a&&b.added}).length}).length&&(d=
!0)}break;case "remove":f(c.items)&&(d=!0);break;case "refresh":d=!0;break;case "move":!this._sort&&f(c.items)&&(d=!0);break;default:throw"Unknown array operation '"+c.change+"'.";}d&&this._setResultsStale()}},_setResultsStale:function(a){this._resultsStale=!0;a?this._deferredResultsStaleEvent=!0:this._raiseResultsStaleEvent()},_addEntity:function(a){f.DataSource.prototype._addEntity.apply(this,arguments);this._filter&&!this._filter(a)&&this._setResultsStale()},_flushDeferredEvents:function(){this._deferredResultsStaleEvent&&
this._raiseResultsStaleEvent()}})})(this,Microsoft.ServiceModel.DomainServices);
(function(j){function f(a,c){if(c){var b=a.__dataSource__;b&&b.destroy();b=Microsoft.ServiceModel.DomainServices;if(c.serviceUrl)b=new b.RemoteDataSource(c.serviceUrl,c.queryName,c.entityType,{format:c.format,queryParameters:c.queryParameters,bufferChanges:c.bufferChanges,dataContext:c.dataContext,entityCollection:a});else if(c.inputData)var e=c.inputData.__dataSource__?j.dataSource.unwrapHack(c.inputData):c.inputData,b=new b.LocalDataSource(e,{entityCollection:a});else throw"Must provide either server parameters or an input array.";
b=d(b).options(c);a.__dataSource__=b}return a.__dataSource__}function d(a){function c(a){a=a||{};j.each("filter,sort,paging,refreshing,refresh,committing,commit,queryResultsStale,entityStateChange".split(","),function(c,d){b(d,a[d])})}function b(b,c){switch(b){case "filter":a.setFilter(c);break;case "sort":a.setSort(c);break;case "paging":a.setPaging(c);break;case "refreshing":e=c;break;case "refresh":f=c;break;case "committing":g=c;break;case "commit":i=c;break;case "queryResultsStale":h=c;break;
case "entityStateChange":l=c;break;default:throw"Unrecognized option '"+b+"'";}}var e,f,g,i,h,l,m,n={refreshStart:function(){j(m).trigger("datasourcerefreshing",arguments);e&&e.apply(null,arguments)},refresh:function(){j(m).trigger("datasourcerefresh",arguments);f&&f.apply(null,arguments)},commitStart:function(){j(m).trigger("datasourcecommitting",arguments);g&&g.apply(null,arguments)},commit:function(){j(m).trigger("datasourcecommit",arguments);i&&i.apply(null,arguments)},resultsStale:function(){j(m).trigger("datasourcequeryresultsstale",
arguments);h&&h.apply(null,arguments)},entityStateChanged:function(){j(m).trigger("datasourceentitiestatechange",arguments);l&&l.apply(null,arguments)}};a.addObserver(n);return m={applyLocalQuery:function(b){var c=new Microsoft.ServiceModel.DomainServices.LocalDataSource(a),e=c.getEntities();e.__dataSource__=d(c);e.__dataSource__.options(b);return e},options:function(a){c(a);return this},option:function(a,c){b(a,c);return this},refresh:function(b){if(b){var d;j.each(b,function(a){"all"!==a&&"completed"!==
a&&(d=!0)});d&&c(b)}a.refresh(b);return this},commitChanges:function(){a.commitChanges();return this},revertChanges:function(b,c){"object"===typeof b?a.revertChange(b,c):a.revertChanges(!!b);return this},destroy:function(){a&&(delete a.getEntities().__dataSource__,a.removeObserver(n),a.dispose(),a=null);return this},getEntities:function(){return a.getEntities()},getEntityState:function(b){return a.getEntityState(b)},getEntityValidationRules:function(){return a.getEntityValidationRules()},getErrors:function(){return a.getErrors()},
isPropertyChanged:function(b,c){return a.isPropertyChanged(b,c)},dataContext:function(){return a.getDataContext()},getTotalCount:function(){return a.getTotalEntityCount()},getEntityId:function(b){return a.getEntityId(b)},_dataSource:a}}j.fn.extend({dataSource:function(a){return f(this[0],a)}});j.dataSource=function(a){if(a){var c=a.entityCollection||[];delete a.entityCollection;return f(c,a)}throw"Provide construction options to $.dataSource";};j.dataSource.wrapHack=function(a,c){a.__dataSource__=
d(c)};j.dataSource.unwrapHack=function(a){return a.__dataSource__._dataSource}})(jQuery);
(function(j,f,d){function a(a){var c={};if(a.$filter||a.filter)c.$filter=a.$filter||a.filter;else if(a.filters){var d=function(a,b,c){"string"===typeof c&&(c="'"+c+"'");switch(b){case "<":return a+" lt "+c;case "<=":return a+" le "+c;case "==":return a+" eq "+c;case "!=":return a+" ne "+c;case ">=":return a+" ge "+c;case ">":return a+" gt "+c;case "StartsWith":return"startswith("+a+","+c+") eq true";case "EndsWith":return"endswith("+a+","+c+") eq true";case "Contains":return"substringof("+c+","+a+
") eq true";default:throw"The operator '"+b+"' is not supported.";}};c.$filter=$.map(a.filters,function(a){return d(a.filterProperty,a.filterOperator,a.filterValue)}).join(" and ")}if(a.$orderby||a.orderby)c.$orderby=a.$orderby||a.orderby;else if(a.sort){var g="",f=function(a){return"descending"===a.direction?a.property+" desc":a.property},g="string"===typeof a.sort?a.sort:$.isArray(a.sort)?$.map(a.sort,function(a){return f(a)}).join():f(a.sort);c.$orderby=g}if(a.$skip||a.skip)c.$skip=a.$skip||a.skip;
if(a.$take||a.take||a.$top||a.top)c.$top=a.$take||a.take||a.$top||a.top;if(a.$expand||a.expand)c.$expand=a.$expand||a.expand;if(a.$format||a.format)c.$format=a.$format||a.format;if(a.$select||a.select)c.$select=a.$select||a.select;if(a.$inlinecount||a.inlinecount)c.$inlinecount=a.$inlinecount||a.inlinecount;else if(a.$includeTotalCount||a.includeTotalCount)c.$inlinecount="allpages";return c}function c(a){for(var d in a){var f=a[d];if(null!==f)if($.isArray(f))for(var g in f)c(g);else if("object"===
typeof f){var i;a:{i=0;var h=void 0;for(h in f)if(1<++i){i=!1;break a}i=!!f.results}i&&(a[d]=f=f.results);c(f)}else f&&f.match&&f.match(/\/Date\([+\-]?\d+[+\-]?\d*\)\//)&&(a[d]=new Date(+f.replace(/\/Date\(([+\-]?\d+)[+\-]?\d*\)\//,"$1")))}return a}f.ODataDataProvider=f.defineClass(function(a){this._serviceUrl=a},{get:function(b,c,d){var f=this._serviceUrl,f="/"!==f.substring(f.length-1)?f+"/":f,i=[];$.each($.extend({},c,a(d||{})),function(a,b){i.push(a.toString()+"="+b.toString())});var c=i.length?
"?"+i.join("&"):"",h=$.Deferred();OData.read(f+b+c,function(a){h.resolve(a)},function(a){h.reject(a)});return h},load:function(a,e){var f=c(a.results),g=f.length&&f[0].__metadata.type;g&&e.addMetadata(g,{getServerId:function(a){return a.__metadata.uri}});var f=e.merge(f,g),i=a.__count;return{entities:f,type:g,totalCount:i===d?null:+i}},post:function(){throw"Saving edits through the OData data provider is not supported.";}})})(this,Microsoft.ServiceModel.DomainServices);
