define(["jquerypp/util/vector","jquerypp/event/livehack","jquery"],function(k,l,j){(function(c){var h=function(a,b){var e=Array.prototype.slice.call(arguments,2);return function(){var d=[this].concat(e,c.makeArray(arguments));return b.apply(a,d)}},g=c.event,i=window.getSelection?function(){window.getSelection().removeAllRanges()}:function(){};c.Drag=function(){};c.extend(c.Drag,{lowerName:"drag",current:null,distance:0,mousedown:function(a,b){if((0===a.button||1==a.button)&&!this.current){var e=new c.Drag,
d=a.delegateTarget||b,f=a.handleObj.selector,h=this;this.current=e;e.setup({element:b,delegate:a.delegateTarget||b,selector:a.handleObj.selector,moved:!1,_distance:this.distance,callbacks:{dragdown:g.find(d,["dragdown"],f),draginit:g.find(d,["draginit"],f),dragover:g.find(d,["dragover"],f),dragmove:g.find(d,["dragmove"],f),dragout:g.find(d,["dragout"],f),dragend:g.find(d,["dragend"],f)},destroyed:function(){h.current=null}},a)}}});c.extend(c.Drag.prototype,{setup:function(a,b){c.extend(this,a);this.element=
c(this.element);this.event=b;this.allowOtherDrags=this.moved=!1;var e=h(this,this.mousemove),d=h(this,this.mouseup);this._mousemove=e;this._mouseup=d;this._distance=a.distance?a.distance:0;this.mouseStartPosition=b.vector();c(document).bind("mousemove",e);c(document).bind("mouseup",d);this.callEvents("down",this.element,b)||(this.noSelection(this.delegate),i())},destroy:function(){c(document).unbind("mousemove",this._mousemove);c(document).unbind("mouseup",this._mouseup);this.moved||(this.event=this.element=
null);this.selection(this.delegate);this.destroyed()},mousemove:function(a,b){if(!this.moved){if(Math.sqrt(Math.pow(b.pageX-this.event.pageX,2)+Math.pow(b.pageY-this.event.pageY,2))<this._distance)return!1;this.init(this.element,b);this.moved=!0}var c=b.vector();(!this._start_position||!this._start_position.equals(c))&&this.draw(c,b)},mouseup:function(a,b){this.moved&&this.end(b);this.destroy()},noSelection:function(a){a=a||this.delegate;document.documentElement.onselectstart=function(){return!1};
document.documentElement.unselectable="on";this.selectionDisabled=this.selectionDisabled?this.selectionDisabled.add(a):c(a);this.selectionDisabled.css("-moz-user-select","-moz-none")},selection:function(){this.selectionDisabled&&(document.documentElement.onselectstart=function(){},document.documentElement.unselectable="off",this.selectionDisabled.css("-moz-user-select",""))},init:function(a,b){var a=c(a),e=this.movingElement=this.element=c(a);this._cancelled=!1;this.event=b;this.mouseElementPosition=
this.mouseStartPosition.minus(this.element.offsetv());this.callEvents("init",a,b);!0!==this._cancelled&&(this.startPosition=e!=this.movingElement?this.movingElement.offsetv():this.currentDelta(),this.makePositioned(this.movingElement),this.oldZIndex=this.movingElement.css("zIndex"),this.movingElement.css("zIndex",1E3),!this._only&&this.constructor.responder&&this.constructor.responder.compile(b,this))},makePositioned:function(a){var b;b=a.css("position");if(!b||"static"==b)b={position:"relative"},
window.opera&&(b.top="0px",b.left="0px"),a.css(b)},callEvents:function(a,b,c,d){for(var f=this.callbacks[this.constructor.lowerName+a],a=0;a<f.length;a++)f[a].call(b,c,this,d);return f.length},currentDelta:function(){return new c.Vector(parseInt(this.movingElement.css("left"),10)||0,parseInt(this.movingElement.css("top"),10)||0)},draw:function(a,b){this._cancelled||(i(),this.location=a.minus(this.mouseElementPosition),this.move(b),this._cancelled||(b.isDefaultPrevented()||this.position(this.location),
!this._only&&this.constructor.responder&&this.constructor.responder.show(a,this,b)))},position:function(a){var b=this.currentDelta(),b=this.movingElement.offsetv().minus(b);this.required_css_position=a.minus(b);this.offsetv=a;a=this.movingElement[0].style;!this._cancelled&&!this._horizontal&&(a.top=this.required_css_position.top()+"px");!this._cancelled&&!this._vertical&&(a.left=this.required_css_position.left()+"px")},move:function(a){this.callEvents("move",this.element,a)},over:function(a,b){this.callEvents("over",
this.element,a,b)},out:function(a,b){this.callEvents("out",this.element,a,b)},end:function(a){if(!this._cancelled){!this._only&&this.constructor.responder&&this.constructor.responder.end(a,this);this.callEvents("end",this.element,a);if(this._revert){var b=this;this.movingElement.animate({top:this.startPosition.top()+"px",left:this.startPosition.left()+"px"},function(){b.cleanup.apply(b,arguments)})}else this.cleanup();this.event=null}},cleanup:function(){this.movingElement.css({zIndex:this.oldZIndex});
this.movingElement[0]!==this.element[0]&&!this.movingElement.has(this.element[0]).length&&!this.element.has(this.movingElement[0]).length&&this.movingElement.css({display:"none"});this._removeMovingElement&&this.movingElement.remove();this.movingElement=this.element=this.event=null},cancel:function(){this._cancelled=!0;!this._only&&this.constructor.responder&&this.constructor.responder.clear(this.event.vector(),this,this.event);this.destroy()},ghost:function(a){var b=this.movingElement.clone().css("position",
"absolute");a?c(a).append(b):c(this.movingElement).after(b);b.width(this.movingElement.width()).height(this.movingElement.height());b.offset(this.movingElement.offset());this.movingElement=b;this.noSelection(b);this._removeMovingElement=!0;return b},representative:function(a,b,e){this._offsetX=b||0;this._offsetY=e||0;b=this.mouseStartPosition;this.movingElement=c(a);this.movingElement.css({top:b.y()-this._offsetY+"px",left:b.x()-this._offsetX+"px",display:"block",position:"absolute"}).show();this.noSelection(this.movingElement);
this.mouseElementPosition=new c.Vector(this._offsetX,this._offsetY);return this},revert:function(a){this._revert=void 0===a?!0:a;return this},vertical:function(){this._vertical=!0;return this},horizontal:function(){this._horizontal=!0;return this},only:function(a){return this._only=void 0===a?!0:a},distance:function(a){return void 0!==a?(this._distance=a,this):this._distance}});g.setupHelper("dragdown,draginit,dragover,dragmove,dragout,dragend".split(","),"mousedown",function(a){c.Drag.mousedown.call(c.Drag,
a,this)})})(j)});
