define(function(){return function(k){k.effects||function(c,l){var n=!1!==c.uiBackCompat;c.effects={effect:{}};(function(){function h(a){var b;return a&&a.constructor===Array&&3===a.length?a:(b=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(b[1],10),parseInt(b[2],10),parseInt(b[3],10)]:(b=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(b[1]),2.55*parseFloat(b[2]),2.55*parseFloat(b[3])]:
(b=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(b[1],16),parseInt(b[2],16),parseInt(b[3],16)]:(b=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(b[1]+b[1],16),parseInt(b[2]+b[2],16),parseInt(b[3]+b[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?d.transparent:d[c.trim(a).toLowerCase()]}c.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,borderColor,color,outlineColor".split(","),function(a,b){c.fx.step[b]=function(a){if(!a.colorInit){var e;
e=a.elem;var d=b,f;do{if((f=c.css(e,d))&&"transparent"!==f||c.nodeName(e,"body"))break;d="backgroundColor"}while(e=e.parentNode);e=h(f);a.start=e;a.end=h(a.end);a.colorInit=!0}a.elem.style[b]="rgb("+Math.max(Math.min(parseInt(a.pos*(a.end[0]-a.start[0])+a.start[0],10),255),0)+","+Math.max(Math.min(parseInt(a.pos*(a.end[1]-a.start[1])+a.start[1],10),255),0)+","+Math.max(Math.min(parseInt(a.pos*(a.end[2]-a.start[2])+a.start[2],10),255),0)+")"}});var d={aqua:[0,255,255],azure:[240,255,255],beige:[245,
245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,
144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]}})();(function(){function h(){var b=this.ownerDocument.defaultView?this.ownerDocument.defaultView.getComputedStyle(this,null):this.currentStyle,a={},e,d;if(b&&b.length&&
b[0]&&b[b[0]])for(d=b.length;d--;)e=b[d],"string"===typeof b[e]&&(a[c.camelCase(e)]=b[e]);else for(e in b)"string"===typeof b[e]&&(a[e]=b[e]);return a}var d=["add","remove","toggle"],a={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};c.each(["borderLeftStyle","borderRightStyle","borderBottomStyle","borderTopStyle"],function(b,a){c.fx.step[a]=function(b){if("none"!==b.end&&!b.setAttr||1===b.pos&&!b.setAttr)k.style(b.elem,a,b.end),b.setAttr=
!0}});c.effects.animateClass=function(b,i,e,g){var f=c.speed(i,e,g);return this.queue(function(){var i=c(this),e=i.attr("class")||"",g,j=f.children?i.find("*").andSelf():i,j=j.map(function(){return{el:c(this),start:h.call(this)}});g=function(){c.each(d,function(a,c){if(b[c])i[c+"Class"](b[c])})};g();j=j.map(function(){this.end=h.call(this.el[0]);var b=this.start,i=this.end,e={},d,f;for(d in i)if(f=i[d],b[d]!==f&&!a[d]&&(c.fx.step[d]||!isNaN(parseFloat(f))))e[d]=f;this.diff=e;return this});i.attr("class",
e);j=j.map(function(){var b=this,a=c.Deferred();this.el.animate(this.diff,k.extend({},f,{queue:!1,complete:function(){a.resolve(b)}}));return a.promise()});c.when.apply(c,j.get()).done(function(){g();c.each(arguments,function(){var b=this.el;c.each(this.diff,function(a){b.css(a,"")})});f.complete.call(i[0])})})};c.fn.extend({_addClass:c.fn.addClass,addClass:function(b,a,e,d){return a?c.effects.animateClass.apply(this,[{add:b},a,e,d]):this._addClass(b)},_removeClass:c.fn.removeClass,removeClass:function(b,
a,e,d){return a?c.effects.animateClass.apply(this,[{remove:b},a,e,d]):this._removeClass(b)},_toggleClass:c.fn.toggleClass,toggleClass:function(b,a,e,d,f){return"boolean"===typeof a||a===l?e?c.effects.animateClass.apply(this,[a?{add:b}:{remove:b},e,d,f]):this._toggleClass(b,a):c.effects.animateClass.apply(this,[{toggle:b},a,e,d])},switchClass:function(a,i,d,g,f){return c.effects.animateClass.apply(this,[{add:i,remove:a},d,g,f])}})})();(function(){function h(a,b,d,e){c.isPlainObject(a)&&(b=a,a=a.effect);
a={effect:a};b===l&&(b={});c.isFunction(b)&&(e=b,d=null,b={});if("number"===typeof b||c.fx.speeds[b])e=d,d=b,b={};c.isFunction(d)&&(e=d,d=null);b&&c.extend(a,b);d=d||b.duration;a.duration=c.fx.off?0:"number"===typeof d?d:d in c.fx.speeds?c.fx.speeds[d]:c.fx.speeds._default;a.complete=e||b.complete;return a}function d(a){return!a||"number"===typeof a||c.fx.speeds[a]?!0:"string"===typeof a&&!c.effects.effect[a]?n&&c.effects[a]?!1:!0:!1}c.extend(c.effects,{version:"@VERSION",save:function(a,b){for(var c=
0;c<b.length;c++)null!==b[c]&&a.data("ui-effects-"+b[c],a[0].style[b[c]])},restore:function(a,b){for(var c=0;c<b.length;c++)null!==b[c]&&a.css(b[c],a.data("ui-effects-"+b[c]))},setMode:function(a,b){"toggle"===b&&(b=a.is(":hidden")?"show":"hide");return b},getBaseline:function(a,b){var c,d;switch(a[0]){case "top":c=0;break;case "middle":c=0.5;break;case "bottom":c=1;break;default:c=a[0]/b.height}switch(a[1]){case "left":d=0;break;case "center":d=0.5;break;case "right":d=1;break;default:d=a[1]/b.width}return{x:d,
y:c}},createWrapper:function(a){if(a.parent().is(".ui-effects-wrapper"))return a.parent();var b={width:a.outerWidth(!0),height:a.outerHeight(!0),"float":a.css("float")},d=c("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),e={width:a.width(),height:a.height()},g=document.activeElement;try{g.id}catch(f){g=document.body}a.wrap(d);(a[0]===g||c.contains(a[0],g))&&c(g).focus();d=a.parent();"static"===a.css("position")?(d.css({position:"relative"}),
a.css({position:"relative"})):(c.extend(b,{position:a.css("position"),zIndex:a.css("z-index")}),c.each(["top","left","bottom","right"],function(c,d){b[d]=a.css(d);isNaN(parseInt(b[d],10))&&(b[d]="auto")}),a.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));a.css(e);return d.css(b).show()},removeWrapper:function(a){var b=document.activeElement;a.parent().is(".ui-effects-wrapper")&&(a.parent().replaceWith(a),(a[0]===b||c.contains(a[0],b))&&c(b).focus());return a},setTransition:function(a,
b,d,e){e=e||{};c.each(b,function(b,c){var h=a.cssUnit(c);0<h[0]&&(e[c]=h[0]*d+h[1])});return e}});c.fn.extend({effect:function(a,b,d,e){function g(a){function b(){c.isFunction(e)&&e.call(d[0]);c.isFunction(a)&&a()}var d=c(this),e=f.complete,g=f.mode;(d.is(":hidden")?"hide"===g:"show"===g)?b():m.call(d[0],f,b)}var f=h.apply(this,arguments),k=f.mode,l=f.queue,m=c.effects.effect[f.effect],j=!m&&n&&c.effects[f.effect];return c.fx.off||!m&&!j?k?this[k](f.duration,f.complete):this.each(function(){f.complete&&
f.complete.call(this)}):m?!1===l?this.each(g):this.queue(l||"fx",g):j.call(this,{options:f,duration:f.duration,callback:f.complete,mode:f.mode})},_show:c.fn.show,show:function(a){if(d(a))return this._show.apply(this,arguments);var b=h.apply(this,arguments);b.mode="show";return this.effect.call(this,b)},_hide:c.fn.hide,hide:function(a){if(d(a))return this._hide.apply(this,arguments);var b=h.apply(this,arguments);b.mode="hide";return this.effect.call(this,b)},__toggle:c.fn.toggle,toggle:function(a){if(d(a)||
"boolean"===typeof a||c.isFunction(a))return this.__toggle.apply(this,arguments);var b=h.apply(this,arguments);b.mode="toggle";return this.effect.call(this,b)},cssUnit:function(a){var b=this.css(a),d=[];c.each(["em","px","%","pt"],function(a,c){0<b.indexOf(c)&&(d=[parseFloat(b),c])});return d}})})();(function(){var h={};c.each(["Quad","Cubic","Quart","Quint","Expo"],function(c,a){h[a]=function(a){return Math.pow(a,c+2)}});c.extend(h,{Sine:function(c){return 1-Math.cos(c*Math.PI/2)},Circ:function(c){return 1-
Math.sqrt(1-c*c)},Elastic:function(c){return 0===c||1===c?c:-Math.pow(2,8*(c-1))*Math.sin((80*(c-1)-7.5)*Math.PI/15)},Back:function(c){return c*c*(3*c-2)},Bounce:function(c){for(var a,b=4;c<((a=Math.pow(2,--b))-1)/11;);return 1/Math.pow(4,3-b)-7.5625*Math.pow((3*a-2)/22-c,2)}});c.each(h,function(d,a){c.easing["easeIn"+d]=a;c.easing["easeOut"+d]=function(b){return 1-a(1-b)};c.easing["easeInOut"+d]=function(b){return 0.5>b?a(2*b)/2:1-a(-2*b+2)/2}})})()}(k)}});
