define(function(){return function(l){(function(d){d.widget("ui.slider",d.ui.mouse,{version:"@VERSION",widgetEventPrefix:"slide",options:{animate:!1,distance:0,max:100,min:0,orientation:"horizontal",range:!1,step:1,value:0,values:null},_create:function(){var b,a=this.options,c=this.element.find(".ui-slider-handle").addClass("ui-state-default ui-corner-all"),e=a.values&&a.values.length||1,f=[];this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();
this._mouseInit();this.element.addClass("ui-slider ui-slider-"+this.orientation+" ui-widget ui-widget-content ui-corner-all"+(a.disabled?" ui-slider-disabled ui-disabled":""));this.range=d([]);a.range&&(!0===a.range&&(a.values||(a.values=[this._valueMin(),this._valueMin()]),a.values.length&&2!==a.values.length&&(a.values=[a.values[0],a.values[0]])),this.range=d("<div></div>").appendTo(this.element).addClass("ui-slider-range ui-widget-header"+("min"===a.range||"max"===a.range?" ui-slider-range-"+a.range:
"")));for(b=c.length;b<e;b++)f.push("<a class='ui-slider-handle ui-state-default ui-corner-all' href='#'></a>");this.handles=c.add(d(f.join("")).appendTo(this.element));this.handle=this.handles.eq(0);this.handles.add(this.range).filter("a").click(function(a){a.preventDefault()}).mouseenter(function(){a.disabled||d(this).addClass("ui-state-hover")}).mouseleave(function(){d(this).removeClass("ui-state-hover")}).focus(function(){a.disabled?d(this).blur():(d(".ui-slider .ui-state-focus").removeClass("ui-state-focus"),
d(this).addClass("ui-state-focus"))}).blur(function(){d(this).removeClass("ui-state-focus")});this.handles.each(function(a){d(this).data("ui-slider-handle-index",a)});this._on(this.handles,{keydown:function(a){var b,c,e,f=d(a.target).data("ui-slider-handle-index");switch(a.keyCode){case d.ui.keyCode.HOME:case d.ui.keyCode.END:case d.ui.keyCode.PAGE_UP:case d.ui.keyCode.PAGE_DOWN:case d.ui.keyCode.UP:case d.ui.keyCode.RIGHT:case d.ui.keyCode.DOWN:case d.ui.keyCode.LEFT:if(a.preventDefault(),!this._keySliding&&
(this._keySliding=!0,d(a.target).addClass("ui-state-active"),b=this._start(a,f),!1===b))return}e=this.options.step;b=this.options.values&&this.options.values.length?c=this.values(f):c=this.value();switch(a.keyCode){case d.ui.keyCode.HOME:c=this._valueMin();break;case d.ui.keyCode.END:c=this._valueMax();break;case d.ui.keyCode.PAGE_UP:c=this._trimAlignValue(b+(this._valueMax()-this._valueMin())/5);break;case d.ui.keyCode.PAGE_DOWN:c=this._trimAlignValue(b-(this._valueMax()-this._valueMin())/5);break;
case d.ui.keyCode.UP:case d.ui.keyCode.RIGHT:if(b===this._valueMax())return;c=this._trimAlignValue(b+e);break;case d.ui.keyCode.DOWN:case d.ui.keyCode.LEFT:if(b===this._valueMin())return;c=this._trimAlignValue(b-e)}this._slide(a,f,c)},keyup:function(a){var b=d(a.target).data("ui-slider-handle-index");this._keySliding&&(this._keySliding=!1,this._stop(a,b),this._change(a,b),d(a.target).removeClass("ui-state-active"))}});this._refreshValue();this._animateOff=!1},_destroy:function(){this.handles.remove();
this.range.remove();this.element.removeClass("ui-slider ui-slider-horizontal ui-slider-vertical ui-slider-disabled ui-widget ui-widget-content ui-corner-all");this._mouseDestroy()},_mouseCapture:function(b){var a,c,e,f,i,g=this;i=this.options;if(i.disabled)return!1;this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()};this.elementOffset=this.element.offset();a=this._normValueFromMouse({x:b.pageX,y:b.pageY});c=this._valueMax()-this._valueMin()+1;this.handles.each(function(b){var h=
Math.abs(a-g.values(b));c>h&&(c=h,e=d(this),f=b)});!0===i.range&&this.values(1)===i.min&&(f+=1,e=d(this.handles[f]));if(!1===this._start(b,f))return!1;this._mouseSliding=!0;this._handleIndex=f;e.addClass("ui-state-active").focus();i=e.offset();this._clickOffset=!d(b.target).parents().andSelf().is(".ui-slider-handle")?{left:0,top:0}:{left:b.pageX-i.left-e.width()/2,top:b.pageY-i.top-e.height()/2-(parseInt(e.css("borderTopWidth"),10)||0)-(parseInt(e.css("borderBottomWidth"),10)||0)+(parseInt(e.css("marginTop"),
10)||0)};this.handles.hasClass("ui-state-hover")||this._slide(b,f,a);return this._animateOff=!0},_mouseStart:function(){return!0},_mouseDrag:function(b){var a=this._normValueFromMouse({x:b.pageX,y:b.pageY});this._slide(b,this._handleIndex,a);return!1},_mouseStop:function(b){this.handles.removeClass("ui-state-active");this._mouseSliding=!1;this._stop(b,this._handleIndex);this._change(b,this._handleIndex);this._clickOffset=this._handleIndex=null;return this._animateOff=!1},_detectOrientation:function(){this.orientation=
"vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(b){var a;"horizontal"===this.orientation?(a=this.elementSize.width,b=b.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(a=this.elementSize.height,b=b.y-this.elementOffset.top-(this._clickOffset?this._clickOffset.top:0));a=b/a;1<a&&(a=1);0>a&&(a=0);"vertical"===this.orientation&&(a=1-a);b=this._valueMax()-this._valueMin();return this._trimAlignValue(this._valueMin()+a*b)},_start:function(b,
a){var c={handle:this.handles[a],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(a),c.values=this.values());return this._trigger("start",b,c)},_slide:function(b,a,c){var d;if(this.options.values&&this.options.values.length){d=this.values(a?0:1);if(2===this.options.values.length&&!0===this.options.range&&(0===a&&c>d||1===a&&c<d))c=d;c!==this.values(a)&&(d=this.values(),d[a]=c,b=this._trigger("slide",b,{handle:this.handles[a],value:c,values:d}),this.values(a?
0:1),!1!==b&&this.values(a,c,!0))}else c!==this.value()&&(b=this._trigger("slide",b,{handle:this.handles[a],value:c}),!1!==b&&this.value(c))},_stop:function(b,a){var c={handle:this.handles[a],value:this.value()};this.options.values&&this.options.values.length&&(c.value=this.values(a),c.values=this.values());this._trigger("stop",b,c)},_change:function(b,a){if(!this._keySliding&&!this._mouseSliding){var c={handle:this.handles[a],value:this.value()};this.options.values&&this.options.values.length&&(c.value=
this.values(a),c.values=this.values());this._trigger("change",b,c)}},value:function(b){if(arguments.length)this.options.value=this._trimAlignValue(b),this._refreshValue(),this._change(null,0);else return this._value()},values:function(b,a){var c,e,f;if(1<arguments.length)this.options.values[b]=this._trimAlignValue(a),this._refreshValue(),this._change(null,b);else if(arguments.length)if(d.isArray(arguments[0])){c=this.options.values;e=arguments[0];for(f=0;f<c.length;f+=1)c[f]=this._trimAlignValue(e[f]),
this._change(null,f);this._refreshValue()}else return this.options.values&&this.options.values.length?this._values(b):this.value();else return this._values()},_setOption:function(b,a){var c,e=0;d.isArray(this.options.values)&&(e=this.options.values.length);d.Widget.prototype._setOption.apply(this,arguments);switch(b){case "disabled":a?(this.handles.filter(".ui-state-focus").blur(),this.handles.removeClass("ui-state-hover"),this.handles.prop("disabled",!0),this.element.addClass("ui-disabled")):(this.handles.prop("disabled",
!1),this.element.removeClass("ui-disabled"));break;case "orientation":this._detectOrientation();this.element.removeClass("ui-slider-horizontal ui-slider-vertical").addClass("ui-slider-"+this.orientation);this._refreshValue();break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=!1;break;case "values":this._animateOff=!0;this._refreshValue();for(c=0;c<e;c+=1)this._change(null,c);this._animateOff=!1}},_value:function(){var b=this.options.value;return b=this._trimAlignValue(b)},
_values:function(b){var a,c;if(arguments.length)return a=this.options.values[b],a=this._trimAlignValue(a);a=this.options.values.slice();for(c=0;c<a.length;c+=1)a[c]=this._trimAlignValue(a[c]);return a},_trimAlignValue:function(b){if(b<=this._valueMin())return this._valueMin();if(b>=this._valueMax())return this._valueMax();var a=0<this.options.step?this.options.step:1,c=(b-this._valueMin())%a,b=b-c;2*Math.abs(c)>=a&&(b+=0<c?a:-a);return parseFloat(b.toFixed(5))},_valueMin:function(){return this.options.min},
_valueMax:function(){return this.options.max},_refreshValue:function(){var b,a,c,e,f,i=this.options.range,g=this.options,j=this,h=!this._animateOff?g.animate:!1,k={};if(this.options.values&&this.options.values.length)this.handles.each(function(c){a=100*((j.values(c)-j._valueMin())/(j._valueMax()-j._valueMin()));k["horizontal"===j.orientation?"left":"bottom"]=a+"%";d(this).stop(1,1)[h?"animate":"css"](k,g.animate);if(!0===j.options.range)if("horizontal"===j.orientation){if(0===c)j.range.stop(1,1)[h?
"animate":"css"]({left:a+"%"},g.animate);if(1===c)j.range[h?"animate":"css"]({width:a-b+"%"},{queue:!1,duration:g.animate})}else{if(0===c)j.range.stop(1,1)[h?"animate":"css"]({bottom:a+"%"},g.animate);if(1===c)j.range[h?"animate":"css"]({height:a-b+"%"},{queue:!1,duration:g.animate})}b=a});else{c=this.value();e=this._valueMin();f=this._valueMax();a=f!==e?100*((c-e)/(f-e)):0;k["horizontal"===this.orientation?"left":"bottom"]=a+"%";this.handle.stop(1,1)[h?"animate":"css"](k,g.animate);if("min"===i&&
"horizontal"===this.orientation)this.range.stop(1,1)[h?"animate":"css"]({width:a+"%"},g.animate);if("max"===i&&"horizontal"===this.orientation)this.range[h?"animate":"css"]({width:100-a+"%"},{queue:!1,duration:g.animate});if("min"===i&&"vertical"===this.orientation)this.range.stop(1,1)[h?"animate":"css"]({height:a+"%"},g.animate);if("max"===i&&"vertical"===this.orientation)this.range[h?"animate":"css"]({height:100-a+"%"},{queue:!1,duration:g.animate})}}})})(l)}});
