define(function(){return function(h){(function(c){var f=null;c.widget("ui.menu",{version:"@VERSION",defaultElement:"<ul>",delay:300,options:{menus:"ul",position:{my:"left top",at:"right top"},role:"menu",blur:null,focus:null,select:null},_create:function(){this.activeMenu=this.element;this.element.uniqueId().addClass("ui-menu ui-widget ui-widget-content ui-corner-all").toggleClass("ui-menu-icons",!!this.element.find(".ui-icon").length).attr({role:this.options.role,tabIndex:0}).bind("click"+this.eventNamespace,
c.proxy(function(a){this.options.disabled&&a.preventDefault()},this));this.options.disabled&&this.element.addClass("ui-state-disabled").attr("aria-disabled","true");this._on({"mousedown .ui-menu-item > a":function(a){a.preventDefault()},"click .ui-state-disabled > a":function(a){a.preventDefault()},"click .ui-menu-item:has(a)":function(a){var b=c(a.target);b[0]!==f&&(f=b[0],b.one("click.menu",function(){f=null}),b.closest(".ui-menu-item").is(".ui-state-disabled")||(this.select(a),this._delay(function(){this.element.is(":focus")||
this.element.focus()},20)))},"mouseenter .ui-menu-item":function(a){var b=c(a.currentTarget);b.siblings().children(".ui-state-active").removeClass("ui-state-active");this.focus(a,b)},mouseleave:"collapseAll","mouseleave .ui-menu":"collapseAll",focus:function(a){var b=this.element,d=b.children(".ui-menu-item").eq(0);this._hasScroll()&&!this.active?b.children().each(function(){var a=c(this);if(0<=a.offset().top-b.offset().top)return d=a,!1}):this.active&&(d=this.active);this.focus(a,d)},blur:function(a){this._delay(function(){c.contains(this.element[0],
this.document[0].activeElement)||this.collapseAll(a)})},keydown:"_keydown"});this.refresh();this._on(this.document,{click:function(a){c(a.target).closest(".ui-menu").length||this.collapseAll(a)}})},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".ui-menu").andSelf().removeClass("ui-menu ui-widget ui-widget-content ui-corner-all ui-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".ui-menu-item").removeClass("ui-menu-item").removeAttr("role").removeAttr("aria-disabled").children("a").removeUniqueId().removeClass("ui-corner-all ui-state-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=c(this);a.data("ui-menu-submenu-carat")&&a.remove()});this.element.find(".ui-menu-divider").removeClass("ui-menu-divider ui-widget-content");this._off(c(f),"click")},_keydown:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$&")}var d,e,g,f=!0;switch(a.keyCode){case c.ui.keyCode.PAGE_UP:this.previousPage(a);break;case c.ui.keyCode.PAGE_DOWN:this.nextPage(a);break;case c.ui.keyCode.HOME:this._move("first","first",a);break;case c.ui.keyCode.END:this._move("last","last",a);break;case c.ui.keyCode.UP:this.previous(a);break;case c.ui.keyCode.DOWN:this.next(a);break;case c.ui.keyCode.LEFT:this.collapse(a);break;case c.ui.keyCode.RIGHT:this.active.is(".ui-state-disabled")||this.expand(a);break;case c.ui.keyCode.ENTER:this._activate(a);
break;case c.ui.keyCode.SPACE:this._activate(a);break;case c.ui.keyCode.ESCAPE:this.collapse(a);break;default:f=!1,d=this.previousFilter||"",e=String.fromCharCode(a.keyCode),g=!1,clearTimeout(this.filterTimer),e===d?g=!0:e=d+e,d=this.activeMenu.children(".ui-menu-item").filter(function(){return RegExp("^"+b(e),"i").test(c(this).children("a").text())}),d=g&&-1!==d.index(this.active.next())?this.active.nextAll(".ui-menu-item"):d,d.length||(e=String.fromCharCode(a.keyCode),d=this.activeMenu.children(".ui-menu-item").filter(function(){return RegExp("^"+
b(e),"i").test(c(this).children("a").text())})),d.length?(this.focus(a,d),1<d.length?(this.previousFilter=e,this.filterTimer=this._delay(function(){delete this.previousFilter},1E3)):delete this.previousFilter):delete this.previousFilter}f&&a.preventDefault()},_activate:function(a){this.active.is(".ui-state-disabled")||(this.active.children("a[aria-haspopup='true']").length?this.expand(a):this.select(a))},refresh:function(){var a,b=this.element.find(this.options.menus+":not(.ui-menu)").addClass("ui-menu ui-widget ui-widget-content ui-corner-all").hide().attr({role:this.options.role,
"aria-hidden":"true","aria-expanded":"false"});a=b.add(this.element);a.children(":not( .ui-menu-item ):has( a )").addClass("ui-menu-item").attr("role","presentation").children("a").uniqueId().addClass("ui-corner-all").attr({tabIndex:-1,role:this._itemRole()});a.children(":not(.ui-menu-item)").each(function(){var a=c(this);/[^\-—–\s]/.test(a.text())||a.addClass("ui-widget-content ui-menu-divider")});a.children(".ui-state-disabled").attr("aria-disabled","true");b.each(function(){var a=c(this),b=a.prev("a"),
f=c('<span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span>').data("ui-menu-submenu-carat",!0);b.attr("aria-haspopup","true").prepend(f);a.attr("aria-labelledby",b.attr("id"))})},_itemRole:function(){return{menu:"menuitem",listbox:"option"}[this.options.role]},focus:function(a,b){var d;this.blur(a,a&&"focus"===a.type);this._scrollIntoView(b);this.active=b.first();d=this.active.children("a").addClass("ui-state-focus");this.options.role&&this.element.attr("aria-activedescendant",d.attr("id"));
this.active.parent().closest(".ui-menu-item").children("a:first").addClass("ui-state-active");a&&"keydown"===a.type?this._close():this.timer=this._delay(function(){this._close()},this.delay);d=c("> .ui-menu",b);d.length&&/^mouse/.test(a.type)&&this._startOpening(d);this.activeMenu=b.parent();this._trigger("focus",a,{item:b})},_scrollIntoView:function(a){var b,d,e;this._hasScroll()&&(b=parseFloat(c.css(this.activeMenu[0],"borderTopWidth"))||0,d=parseFloat(c.css(this.activeMenu[0],"paddingTop"))||0,
b=a.offset().top-this.activeMenu.offset().top-b-d,d=this.activeMenu.scrollTop(),e=this.activeMenu.height(),a=a.height(),0>b?this.activeMenu.scrollTop(d+b):b+a>e&&this.activeMenu.scrollTop(d+b-e+a))},blur:function(a,b){b||clearTimeout(this.timer);this.active&&(this.active.children("a").removeClass("ui-state-focus"),this.active=null,this._trigger("blur",a,{item:this.active}))},_startOpening:function(a){clearTimeout(this.timer);"true"===a.attr("aria-hidden")&&(this.timer=this._delay(function(){this._close();
this._open(a)},this.delay))},_open:function(a){var b=c.extend({of:this.active},"function"===c.type(this.options.position)?this.options.position(this.active):this.options.position);clearTimeout(this.timer);this.element.find(".ui-menu").not(a.parents()).hide().attr("aria-hidden","true");a.show().removeAttr("aria-hidden").attr("aria-expanded","true").position(b)},collapseAll:function(a,b){clearTimeout(this.timer);this.timer=this._delay(function(){var d=b?this.element:c(a&&a.target).closest(this.element.find(".ui-menu"));
d.length||(d=this.element);this._close(d);this.blur(a);this.activeMenu=d},this.delay)},_close:function(a){a||(a=this.active?this.active.parent():this.element);a.find(".ui-menu").hide().attr("aria-hidden","true").attr("aria-expanded","false").end().find("a.ui-state-active").removeClass("ui-state-active")},collapse:function(a){var b=this.active&&this.active.parent().closest(".ui-menu-item",this.element);if(b&&b.length)return this._close(),this.focus(a,b),!0},expand:function(a){var b=this.active&&this.active.children(".ui-menu ").children(".ui-menu-item").first();
if(b&&b.length)return this._open(b.parent()),this._delay(function(){this.focus(a,b)},20),!0},next:function(a){this._move("next","first",a)},previous:function(a){this._move("prev","last",a)},isFirstItem:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},isLastItem:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},_move:function(a,b,d){var c;this.active&&(c="first"===a||"last"===a?this.active["first"===a?"prevAll":"nextAll"](".ui-menu-item").eq(-1):
this.active[a+"All"](".ui-menu-item").eq(0));if(!c||!c.length||!this.active)c=this.activeMenu.children(".ui-menu-item")[b]();this.focus(d,c)},nextPage:function(a){if(this.active){if(!this.isLastItem())if(this._hasScroll()){var b=this.active.offset().top,d=this.element.height(),e;this.active.nextAll(".ui-menu-item").each(function(){e=c(this);return 0>c(this).offset().top-b-d});this.focus(a,e)}else this.focus(a,this.activeMenu.children(".ui-menu-item")[!this.active?"first":"last"]())}else this._move("next",
"first",a)},previousPage:function(a){if(this.active){if(!this.isFirstItem())if(this._hasScroll()){var b=this.active.offset().top,d=this.element.height(),e;this.active.prevAll(".ui-menu-item").each(function(){e=c(this);return 0<c(this).offset().top-b+d});this.focus(a,e)}else this.focus(a,this.activeMenu.children(".ui-menu-item").first())}else this._move("next","first",a)},_hasScroll:function(){return this.element.outerHeight()<this.element.prop("scrollHeight")},select:function(a){var b={item:this.active};
this.collapseAll(a,!0);this._trigger("select",a,b)}})})(h)}});
