define(function(){return function(h){(function(b,h){var i={buttons:!0,height:!0,maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0,width:!0},j={maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0};b.widget("ui.dialog",{version:"@VERSION",options:{autoOpen:!0,buttons:{},closeOnEscape:!0,closeText:"close",dialogClass:"",draggable:!0,hide:null,height:"auto",maxHeight:!1,maxWidth:!1,minHeight:150,minWidth:150,modal:!1,position:{my:"center",at:"center",of:window,collision:"fit",using:function(a){var c=b(this).css(a).offset().top;
0>c&&b(this).css("top",a.top-c)}},resizable:!0,show:null,stack:!0,title:"",width:300,zIndex:1E3},_create:function(){this.originalTitle=this.element.attr("title");"string"!==typeof this.originalTitle&&(this.originalTitle="");this.oldPosition={parent:this.element.parent(),index:this.element.parent().children().index(this.element)};this.options.title=this.options.title||this.originalTitle;var a=this,c=this.options,d=c.title||"&#160;",e=(this.uiDialog=b("<div>")).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+
c.dialogClass).css({display:"none",outline:0,zIndex:c.zIndex}).attr("tabIndex",-1).keydown(function(d){c.closeOnEscape&&!d.isDefaultPrevented()&&d.keyCode&&d.keyCode===b.ui.keyCode.ESCAPE&&(a.close(d),d.preventDefault())}).mousedown(function(b){a.moveToTop(!1,b)}).appendTo("body");this.element.show().removeAttr("title").addClass("ui-dialog-content ui-widget-content").appendTo(e);var f=(this.uiDialogTitlebar=b("<div>")).addClass("ui-dialog-titlebar  ui-widget-header  ui-corner-all  ui-helper-clearfix").prependTo(e),
g=b("<a href='#'></a>").addClass("ui-dialog-titlebar-close  ui-corner-all").attr("role","button").click(function(b){b.preventDefault();a.close(b)}).appendTo(f);(this.uiDialogTitlebarCloseText=b("<span>")).addClass("ui-icon ui-icon-closethick").text(c.closeText).appendTo(g);var d=b("<span>").uniqueId().addClass("ui-dialog-title").html(d).prependTo(f),k=(this.uiDialogButtonPane=b("<div>")).addClass("ui-dialog-buttonpane ui-widget-content ui-helper-clearfix");(this.uiButtonSet=b("<div>")).addClass("ui-dialog-buttonset").appendTo(k);
e.attr({role:"dialog","aria-labelledby":d.attr("id")});f.find("*").add(f).disableSelection();this._hoverable(g);this._focusable(g);c.draggable&&b.fn.draggable&&this._makeDraggable();c.resizable&&b.fn.resizable&&this._makeResizable();this._createButtons(c.buttons);this._isOpen=!1;b.fn.bgiframe&&e.bgiframe()},_init:function(){this.options.autoOpen&&this.open()},_destroy:function(){var a,b=this.oldPosition;this.overlay&&this.overlay.destroy();this.uiDialog.hide();this.element.removeClass("ui-dialog-content ui-widget-content").hide().appendTo("body");
this.uiDialog.remove();this.originalTitle&&this.element.attr("title",this.originalTitle);a=b.parent.children().eq(b.index);a.length?a.before(this.element):b.parent.append(this.element)},widget:function(){return this.uiDialog},close:function(a){var c=this,d,e;if(this._isOpen&&!1!==this._trigger("beforeClose",a))return this._isOpen=!1,this.overlay&&this.overlay.destroy(),this._off(this.uiDialog,"keypress"),this.options.hide?this.uiDialog.hide(this.options.hide,function(){c._trigger("close",a)}):(this.uiDialog.hide(),
this._trigger("close",a)),b.ui.dialog.overlay.resize(),this.options.modal&&(d=0,b(".ui-dialog").each(function(){this!==c.uiDialog[0]&&(e=b(this).css("z-index"),isNaN(e)||(d=Math.max(d,e)))}),b.ui.dialog.maxZ=d),this},isOpen:function(){return this._isOpen},moveToTop:function(a,c){var d=this.options;if(d.modal&&!a||!d.stack&&!d.modal)return this._trigger("focus",c);d.zIndex>b.ui.dialog.maxZ&&(b.ui.dialog.maxZ=d.zIndex);this.overlay&&(b.ui.dialog.maxZ+=1,b.ui.dialog.overlay.maxZ=b.ui.dialog.maxZ,this.overlay.$el.css("z-index",
b.ui.dialog.overlay.maxZ));d={scrollTop:this.element.scrollTop(),scrollLeft:this.element.scrollLeft()};b.ui.dialog.maxZ+=1;this.uiDialog.css("z-index",b.ui.dialog.maxZ);this.element.attr(d);this._trigger("focus",c);return this},open:function(){if(!this._isOpen){var a;a=this.options;var c=this.uiDialog;this._size();this._position(a.position);c.show(a.show);this.overlay=a.modal?new b.ui.dialog.overlay(this):null;this.moveToTop(!0);a.modal&&this._on(c,{keydown:function(a){if(a.keyCode===b.ui.keyCode.TAB){var c=
b(":tabbable",this),f=c.filter(":first"),c=c.filter(":last");if(a.target===c[0]&&!a.shiftKey)return f.focus(1),!1;if(a.target===f[0]&&a.shiftKey)return c.focus(1),!1}}});a=this.element.find(":tabbable");a.length||(a=this.uiDialogButtonPane.find(":tabbable"),a.length||(a=c));a.eq(0).focus();this._isOpen=!0;this._trigger("open");return this}},_createButtons:function(a){var c=this,d=!1;this.uiDialogButtonPane.remove();this.uiButtonSet.empty();"object"===typeof a&&null!==a&&b.each(a,function(){return!(d=
!0)});d?(b.each(a,function(a,d){var d=b.isFunction(d)?{click:d,text:a}:d,g=b("<button type='button'>").attr(d,!0).unbind("click").click(function(){d.click.apply(c.element[0],arguments)}).appendTo(c.uiButtonSet);b.fn.button&&g.button()}),this.uiDialog.addClass("ui-dialog-buttons"),this.uiDialogButtonPane.appendTo(this.uiDialog)):this.uiDialog.removeClass("ui-dialog-buttons")},_makeDraggable:function(){function a(a){return{position:a.position,offset:a.offset}}var c=this,d=this.options;this.uiDialog.draggable({cancel:".ui-dialog-content, .ui-dialog-titlebar-close",
handle:".ui-dialog-titlebar",containment:"document",start:function(d,f){b(this).addClass("ui-dialog-dragging");c._trigger("dragStart",d,a(f))},drag:function(b,d){c._trigger("drag",b,a(d))},stop:function(e,f){d.position=[f.position.left-c.document.scrollLeft(),f.position.top-c.document.scrollTop()];b(this).removeClass("ui-dialog-dragging");c._trigger("dragStop",e,a(f));b.ui.dialog.overlay.resize()}})},_makeResizable:function(a){function c(a){return{originalPosition:a.originalPosition,originalSize:a.originalSize,
position:a.position,size:a.size}}var a=a===h?this.options.resizable:a,d=this,e=this.options,f=this.uiDialog.css("position"),a="string"===typeof a?a:"n,e,s,w,se,sw,ne,nw";this.uiDialog.resizable({cancel:".ui-dialog-content",containment:"document",alsoResize:this.element,maxWidth:e.maxWidth,maxHeight:e.maxHeight,minWidth:e.minWidth,minHeight:this._minHeight(),handles:a,start:function(a,e){b(this).addClass("ui-dialog-resizing");d._trigger("resizeStart",a,c(e))},resize:function(a,b){d._trigger("resize",
a,c(b))},stop:function(a,f){b(this).removeClass("ui-dialog-resizing");e.height=b(this).height();e.width=b(this).width();d._trigger("resizeStop",a,c(f));b.ui.dialog.overlay.resize()}}).css("position",f).find(".ui-resizable-se").addClass("ui-icon ui-icon-grip-diagonal-se")},_minHeight:function(){var a=this.options;return"auto"===a.height?a.minHeight:Math.min(a.minHeight,a.height)},_position:function(a){var c=[],d=[0,0],e;if(a){if("string"===typeof a||"object"===typeof a&&"0"in a)c=a.split?a.split(" "):
[a[0],a[1]],1===c.length&&(c[1]=c[0]),b.each(["left","top"],function(a,b){+c[a]===c[a]&&(d[a]=c[a],c[a]=b)}),a={my:c.join(" "),at:c.join(" "),offset:d.join(" ")};a=b.extend({},b.ui.dialog.prototype.options.position,a)}else a=b.ui.dialog.prototype.options.position;(e=this.uiDialog.is(":visible"))||this.uiDialog.show();this.uiDialog.position(a);e||this.uiDialog.hide()},_setOptions:function(a){var c=this,d={},e=!1;b.each(a,function(a,b){c._setOption(a,b);a in i&&(e=!0);a in j&&(d[a]=b)});e&&this._size();
this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option",d)},_setOption:function(a,c){var d,e=this.uiDialog;switch(a){case "buttons":this._createButtons(c);break;case "closeText":this.uiDialogTitlebarCloseText.text(""+c);break;case "dialogClass":e.removeClass(this.options.dialogClass).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+c);break;case "disabled":c?e.addClass("ui-dialog-disabled"):e.removeClass("ui-dialog-disabled");break;case "draggable":(d=e.is(":data(draggable)"))&&
!c&&e.draggable("destroy");!d&&c&&this._makeDraggable();break;case "position":this._position(c);break;case "resizable":(d=e.is(":data(resizable)"))&&!c&&e.resizable("destroy");d&&"string"===typeof c&&e.resizable("option","handles",c);!d&&!1!==c&&this._makeResizable(c);break;case "title":b(".ui-dialog-title",this.uiDialogTitlebar).html(""+(c||"&#160;"))}this._super(a,c)},_size:function(){var a,c,d=this.options,e=this.uiDialog.is(":visible");this.element.show().css({width:"auto",minHeight:0,height:0});
d.minWidth>d.width&&(d.width=d.minWidth);a=this.uiDialog.css({height:"auto",width:d.width}).outerHeight();c=Math.max(0,d.minHeight-a);"auto"===d.height?b.support.minHeight?this.element.css({minHeight:c,height:"auto"}):(this.uiDialog.show(),a=this.element.css("height","auto").height(),e||this.uiDialog.hide(),this.element.height(Math.max(a,c))):this.element.height(Math.max(d.height-a,0));this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option","minHeight",this._minHeight())}});b.extend(b.ui.dialog,
{uuid:0,maxZ:0,getTitleId:function(a){a=a.attr("id");a||(a=this.uuid+=1);return"ui-dialog-title-"+a},overlay:function(a){this.$el=b.ui.dialog.overlay.create(a)}});b.extend(b.ui.dialog.overlay,{instances:[],oldInstances:[],maxZ:0,events:b.map("focus,mousedown,mouseup,keydown,keypress,click".split(","),function(a){return a+".dialog-overlay"}).join(" "),create:function(a){0===this.instances.length&&(setTimeout(function(){b.ui.dialog.overlay.instances.length&&b(document).bind(b.ui.dialog.overlay.events,
function(a){if(b(a.target).zIndex()<b.ui.dialog.overlay.maxZ)return!1})},1),b(window).bind("resize.dialog-overlay",b.ui.dialog.overlay.resize));var c=this.oldInstances.pop()||b("<div>").addClass("ui-widget-overlay");b(document).bind("keydown.dialog-overlay",function(d){var e=b.ui.dialog.overlay.instances;0!==e.length&&e[e.length-1]===c&&a.options.closeOnEscape&&!d.isDefaultPrevented()&&d.keyCode&&d.keyCode===b.ui.keyCode.ESCAPE&&(a.close(d),d.preventDefault())});c.appendTo(document.body).css({width:this.width(),
height:this.height()});b.fn.bgiframe&&c.bgiframe();this.instances.push(c);return c},destroy:function(a){var c=b.inArray(a,this.instances),d=0;-1!==c&&this.oldInstances.push(this.instances.splice(c,1)[0]);0===this.instances.length&&b([document,window]).unbind(".dialog-overlay");a.height(0).width(0).remove();b.each(this.instances,function(){d=Math.max(d,this.css("z-index"))});this.maxZ=d},height:function(){var a,c;return b.browser.msie?(a=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight),
c=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight),a<c?b(window).height()+"px":a+"px"):b(document).height()+"px"},width:function(){var a,c;return b.browser.msie?(a=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth),c=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth),a<c?b(window).width()+"px":a+"px"):b(document).width()+"px"},resize:function(){var a=b([]);b.each(b.ui.dialog.overlay.instances,function(){a=a.add(this)});a.css({width:0,
height:0}).css({width:b.ui.dialog.overlay.width(),height:b.ui.dialog.overlay.height()})}});b.extend(b.ui.dialog.overlay.prototype,{destroy:function(){b.ui.dialog.overlay.destroy(this.$el)}})})(h)}});
